# 기출문제 제 9회

1. 각 연도 및 성별의 총 대출액의 절댓값 차이를 구하고, 절댓값 차이가 가장 큰 지역코드를 구하시오

In [1]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
#display(df.head(2))
df['Sum debts'] = df['금액1'] + df['금액2']

dfgender = df.groupby(['year','gender','지역코드'])['Sum debts'].sum().reset_index()
#display(dfgender.head(5))

df_pivot = dfgender.pivot_table(index=['year','지역코드'],columns='gender',
                                values='Sum debts',fill_value=0)
'''
df.pivot_table(index='행이 될 열', columns ='열이 될 열', values = '집계할 값', aggfunc = '계산방법'
                , fill_value = '결측치' )
'''
display(df_pivot)

df_pivot['abs_diff'] = abs(df_pivot[0]-df_pivot[1])
max_row = df_pivot[df_pivot['abs_diff']==df_pivot['abs_diff'].max()]
display(max_row.reset_index())
print("지역 코드 : ",max_row.reset_index()['지역코드'][0])

gender           0         1
year 지역코드
2015 101       0.0   87088.0
     118       0.0  100609.0
     130       0.0   41599.0
     131   37881.0       0.0
     150       0.0   56775.0
...            ...       ...
2020 176   85767.0       0.0
     178   71066.0       0.0
     192       0.0  109436.0
     195       0.0   34792.0
     196   76900.0       0.0

[91 rows x 2 columns]

gender  year  지역코드         0    1  abs_diff
0       2018   143  168869.0  0.0  168869.0

지역 코드 :  143

In [16]:
import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
#display(df.head(2))

df.groupby(['year','gender','지역코드'])[['금액1','금액2']].sum()
df['대출총액'] = df['금액1']+df['금액2']
#display(df.head(5))

df_pivot = df.pivot_table(index=['year','지역코드'],columns='gender',fill_value=0,values='대출총액')
display(df_pivot)
df_pivot['abs_diff'] = abs(df_pivot[0]-df_pivot[1])
max_row = df_pivot['abs_diff'].idxmax()
display(max_row)
print(max_row)

gender           0         1
year 지역코드
2015 101       0.0   87088.0
     118       0.0  100609.0
     130       0.0   41599.0
     131   37881.0       0.0
     150       0.0   56775.0
...            ...       ...
2020 176   85767.0       0.0
     178   71066.0       0.0
     192       0.0  109436.0
     195       0.0   34792.0
     196   76900.0       0.0

[91 rows x 2 columns]

(np.int64(2016), np.int64(157))

(np.int64(2016), np.int64(157))

2. 각 연도별 최대 검거율을 가진 범죄유형을 찾아서 해당 연도 및 유형의 검거건수들의 총합을 구하시오.  
(검거율 = 검거건수 / 발생건수)

In [46]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_2.csv")
display(df.head(2))

crime_cols = [f'범죄유형{i}' for i in range(1,11)]
df2 = df.groupby(['연도','구분'])[crime_cols].sum().reset_index()
display(df2.head(5))

df3 = df[df['구분']=='검거건수'].set_index('연도').drop(columns='구분')
df4 = df[df['구분']=='발생건수'].set_index('연도').drop(columns='구분')
dfratio = df3/df4

df_max = dfratio.idxmax(axis=1) # 각 연도별 최대 검거율 가진 범죄유형
dfmax_reset = df_max.reset_index().rename({0: '범죄유형'},axis=1)
display(dfmax_reset)

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,검거건수,302,430,470,187,271,199,220,230,321,408
1,2000,발생건수,302,635,470,306,271,900,220,814,321,666
2,2001,검거건수,121,352,691,613,574,158,476,360,575,513
3,2001,발생건수,969,543,691,613,585,391,476,360,659,513
4,2002,검거건수,120,266,373,487,700,415,113,330,684,445

      연도    범죄유형
0   2000   범죄유형1
1   2001   범죄유형3
2   2002   범죄유형8
3   2003   범죄유형2
4   2004   범죄유형4
5   2005   범죄유형2
6   2006   범죄유형5
7   2007   범죄유형6
8   2008   범죄유형2
9   2009   범죄유형4
10  2010   범죄유형3
11  2011   범죄유형1
12  2012  범죄유형10
13  2013   범죄유형1
14  2014   범죄유형1
15  2015   범죄유형5
16  2016   범죄유형2
17  2017   범죄유형1
18  2018  범죄유형10
19  2019   범죄유형1
20  2020   범죄유형4
21  2021   범죄유형4
22  2022   범죄유형1
23  2023   범죄유형2
24  2024   범죄유형3

3. 제시된 문제를 순서대로 풀고, 해답을 제시하시오

In [68]:
import pandas as pd 
import numpy as np
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_3.csv")
#display(df.head(3))
#print(df.isnull().sum())

# 평균만족도 : 결측치는 평균만족도 컬럼의 전체 평균으로 채우시오
satify_mean = df['평균만족도'].mean()
df['평균만족도'].fillna(satify_mean)

# 근속연수 : 결측치는 각 부서와 등급별 평균 근속연수로 채우시오. (평균값의 소숫점은 버림 처리)
df2 = df.groupby(['부서','등급'])['근속연수'].mean().reset_index()
df = df.merge(df2,on=['부서','등급'],how='left')
display(df)

import pandas as pd
import numpy as np

mean_tenure=(
    df.groupby(["부서","등급"])["근속연수"]
    .mean()
    .apply(np.floor)
    .reset_index()
    .rename(columns={"근속연수":"평균근속연수"})
)
df = df.merge(mean_tenure,on=["부서","등급"],how="left")
df["근속연수"]=np.where(
    df["근속연수"].isnull(),
    df["평균근속연수"],
    df["근속연수"]
)
df.drop(columns=["평균근속연수"],inplace=True)
display(df)

           부서 등급     평균만족도  근속연수_x  교육참가횟수     근속연수_y
0     Finance  C  4.023911    17.0     8.0  11.555556
1   Marketing  A  3.756698    14.0    16.0  19.375000
2          IT  B  2.628697    21.0    13.0  14.800000
3   Marketing  A  3.196616     NaN    18.0  19.375000
4   Marketing  C  4.770665    28.0    10.0  21.833333
..        ... ..       ...     ...     ...        ...
95         IT  A  4.884821    13.0     3.0  16.333333
96  Marketing  A  4.787161    20.0    16.0  19.375000
97      Sales  A  3.425397    15.0     4.0  17.600000
98      Sales  A       NaN     3.0    18.0  17.600000
99         HR  C  4.820796     NaN    17.0  12.000000

[100 rows x 6 columns]

KeyError: 'Column not found: 근속연수'

# 작업형 제2유형

In [ ]:
# 훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오. (Target : 농업 유형 (다중분류, {0, 1, 2}))
# 제출형식은 ID, pred 두 칼럼만 존재해야한다. (평가 지표 : Macro F1 Score)
# 9_2_train, 9_2_test 

import pandas as pd 
import numpy as np
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_2_test.csv")

In [71]:
# EDA
display(train.head(3))
display(test.head(3))
print("\n")
print("Train 데이터 null 여부")
print(train.isnull().sum(),"\n")
print("Train 데이터 Information")
print(train.info())

     ID  지역 등급   농업면적    연도  라벨
0  2089  부산  B  27406  2010   0
1  1964  대전  C  50520  2006   0
2  1820  울산  B  15030  2021   0

     ID  지역 등급   농업면적    연도  라벨
0  1094  경남  B   6902  2020   0
1  1341  전북  A  93327  2016   0
2   545  인천  C   1921  2011   1

Train 데이터 null 여부
ID      0
지역      0
등급      0
농업면적    0
연도      0
라벨      0
dtype: int64

Train 데이터 Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      1680 non-null   int64
 1   지역      1680 non-null   object
 2   등급      1680 non-null   object
 3   농업면적    1680 non-null   int64
 4   연도      1680 non-null   int64
 5   라벨      1680 non-null   int64
dtypes: int64(4), object(2)
memory usage: 78.9+ KB
None

In [74]:
from sklearn.model_selection import train_test_split

test_id = test['ID']
train_X = train.drop(['라벨'],axis=1)
train_y = train['라벨']

test_X = test.drop(['라벨'],axis=1)
test_y = test['라벨']

train_X, valid_X, train_y, valid_y = train_test_split(train_X, train_y,test_size=0.3, random_state=42)

# 데이터 전처리
cat_columns = train_X.select_dtypes('object').columns.to_list()

In [76]:
# 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder

Onehotencoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

train_X_preprocessed = Onehotencoder.fit_transform(train_X[cat_columns])
valid_X_preprocessed = Onehotencoder.transform(valid_X[cat_columns])
test_X_preprocessed = Onehotencoder.transform(test_X[cat_columns])

In [77]:
# 모델 적합
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(train_X_preprocessed,train_y)

# 모형 성능 확인
from sklearn.metrics import f1_score 
pred_val = rf.predict(valid_X_preprocessed)
print("valid f1-macro : ",f1_score(valid_y, pred_val, average='macro'))

valid f1-macro :  0.3107344632768361

In [78]:
# 최종 예측
test_pred = rf.predict(test_X_preprocessed)
test_pred = pd.DataFrame(test_pred, columns=['pred'])

In [79]:
result = pd.concat([test_id, test_pred],axis=1)
print(result.head(2))

     ID  pred
0  1094     0
1  1341     0

In [80]:
# 테스트 데이터로 예측
result = pd.concat([test_id,test_pred],axis=1)
#result.to_csv('9_2_result.csv',index=False)
display(result)

       ID  pred
0    1094     0
1    1341     0
2     545     0
3     225     0
4     690     0
..    ...   ...
715  1488     0
716   172     0
717   768     0
718  1866     0
719   786     0

[720 rows x 2 columns]

# 작업형 제3유형

한 제조 회사에서 생산성을 높이고자 직원들의 주요 생산성 요인을 분석하기로 결정하였다. 이를 위해 200명의 직원 데이터를 수집했으며, 직원들의 근무 기간, 특성 정보, 그리고 개인적인 속성을 조사하였다.  

(1) 모든 칼럼을 활용하여 design 을 예측하는 다중회귀 분석을 시행한 후 유의하지 않은 설명변수 개수를 구하시오. (패널티는 포함되지 않으며, 모델의 절편항은 포함)

(2) 훈련데이터 (학습용 데이터) 의 예측값과 실제값의 피어슨 상관계수를 구하시오 
(훈련데이터 : id1 ~ 140, 테스트 데이터 : id41 ~ 200) 


(3) 적합한 모델을 활용하여 테스트 데이터에서의 RMSE 를 구하시오

In [85]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_3_1.csv")
display(df.head(3))

train = df[:40]
test = df[40:]

   id  tenure         f2  f3         f4         f5     design
0   1       7  58.875116   1  58.929804   8.629778  41.297902
1   2      20  56.054831   0  72.885964  13.040569  47.769777
2   3      15  42.797020   1  75.951039  18.546462  50.628621

In [87]:
from statsmodels.formula.api import ols 

formula = "design ~ tenure + f2 + f3 + f4 + f5"
model = ols(formula,data=train).fit()

p_value = model.pvalues 

non_significant = (p_value[1:]>=0.05).sum()
print("유의하지 않은 설명변수의 갯수 : ",non_significant)

y_pred = model.predict(train)
y_real = train['design']

from scipy.stats import pearsonr 
correlation, _ = pearsonr(y_pred,y_real)
print("상관계수 : ",correlation)

y_pred_test = model.predict(test)
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(test['design'],y_pred_test)
print("RMSE : ",rmse)

유의하지 않은 설명변수의 갯수 :  2
상관계수 :  0.9449554262834206
RMSE :  5.689747314838851

한 통신회사에서는 고객 이탈을 줄이고자 주요 요인들을 분석하기로 결정하였다. 이를 위해 500 명의 고객 데이터를 수집했으며, 고객의 서비스 이용 및 가입 정보, 그리고 일부 개인적인 속성을 조사하였다.  

(1) 고객 이탈을 예측하는 로지스틱 회귀를 시행한 후 col1 칼럼의 p-value 를 구하시오

(2) 폰 서비스를 받지 않은 고객 대비 받은 고객의 이탈 확률 오즈비를 구하시오  

(3) 이탈할 확률이 0.3 이상인 고객 수를 구하시오

In [88]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_3_2.csv")
display(df.head(3))

        col1       col2  Phone_Service  Tech_Insurance  churn
0  54.967142  34.630888              0               1      0
1  48.617357  39.547083              0               0      0
2  56.476885  23.007162              1               0      1

In [91]:
from statsmodels.formula.api import logit

formula = "churn ~ col2 + Phone_Service + Tech_Insurance + col1"
model = logit(formula,data=df).fit()

print("col1 의 p-value : ",round(model.pvalues['col1'],3))

oldds = round(np.exp(model.params['Phone_Service']),3)
print("오즈비 : ",oldds)

# 이탈할 확률이 0.3 이상 
model_prob = model.predict(df)
prob03 = sum(model_prob>0.3)
print("이탈할 확률이 0.3 이상인 고객수 : ",prob03)

Optimization terminated successfully.
         Current function value: 0.640721
         Iterations 5
col1 의 p-value :  0.0
오즈비 :  1.867
이탈할 확률이 0.3 이상인 고객수 :  450