## T3-1 단일표본 T 검정

다음은 22명의 학생들이 국어시험에서 받은 점수이다. 학생들의 평균이 75보다 크다고 할 수 있는가?  
$H_0$ : 모평균은 $\mu$ 와 같다. 학생들의 평균은 75이다.  
$H_1$ : 모평균은 $\mu$ 가 아니다. 학생들의 평균은 75보다 크다.  

가정  
1. 모집단은 정규분포를 따른다.  
2. 표본의 크기가 충분히 크다.  

검정통계량, p-value, 검정결과를 출력하시오

In [1]:
from scipy.stats import ttest_1samp

# 데이터 
scores = [75, 80, 68, 72, 77, 82, 81, 79, 70, 74, 76, 78, 81, 73, 81, 78, 75, 72, 74, 79, 78, 79]

# 모평균 가설검정
mu = 75 # 모평균
alpha = 0.05 # 유의수준

# t-test 를 사용하여 가설 검정
t_statistic, p_value = ttest_1samp(scores, mu, alternative='greater')

print("t-statistic : ",t_statistic)
print("p-value : ",p_value)

if p_value < alpha : 
    print("귀무가설을 기각합니다. 모평균은 75보다 큽니다.")
else :
    print("귀무가설을 채택합니다. 모평균은 75보다 크지 않습니다.")

t-statistic :  1.765879233231226
p-value :  0.04597614747709138
귀무가설을 기각합니다. 모평균은 75보다 큽니다.

ttest_1samp (일표본 t-검정, One-sample t-test)  

- 하나의 표본 집단의 평균이 연구자가 가정한 특정 이론값과 통계적으로 같을지 다를지 검정  
- stats.stats.ttest_1samp(데이터 배열, popmean = 기준값) 
- 자유도 n-1

## T3-2 독립표본 T검정  
어떤 특정 약물을 복용한 사람들의 평균 체온이 복용하지 않은 사람들의 평균 체온과 유의미하게 다른지 검정해보려고 합니다.  

가정 : 
- 약물을 복용한 그룹과 복용하지 않은 그룹의 체온 데이터가 각각 주어져 있다고 가정합니다.
- 각 그룹의 체온은 정규분포를 따른다고 가정합니다.  

검정통계량, p-value, 검정결과를 출력하시오

In [2]:
from scipy import stats 

# 데이터 수집
group1 = [36.8, 36.7, 37.1, 36.9, 37.2, 36.8, 36.9, 37.1, 36.7, 37.1]
group2 = [36.5, 36.6, 36.3, 36.6, 36.9, 36.7, 36.7, 36.8, 36.5, 36.7]

t_statistics, p_value = stats.ttest_ind(group1, group2)

print("검정통계량 : ",t_statistics)
print("p-value : ",p_value)

alpha=0.05

if p_value < alpha:
    print("귀무가설을 기각합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 있습니다.")
else:
    print("귀무가설을 채택합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 없습니다.")

검정통계량 :  3.7964208654863336
p-value :  0.0013218914767036936
귀무가설을 기각합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 있습니다.

stats.ttest_ind (독립표본 t-검정, Independent two-sample t-test)
- 서로 상관이 없는 독립된 두 표본 집단의 평균을 비교하여, 두 모집단의 평균이 같은지 다른지 검정  
- stats.ttest_ind(표본1, 표본2, equal_val=True) 
    - 두 집단의 분산이 같은지 모를 때는 equal_var=False 를 주어 웰치의 t-검정 (Welch's t-test) 를 수행하는것이 더 안전
- 자유도 $n_1+n_2-2$ (등분산 가정시)

## T3-3 대응표본 T검정  

주어진 데이터는 고혈압 환자 치료 전후의 혈압이다.  
해당 치료가 효과가 있는지 대응 (쌍체) 표본 t-검정을 진행하시오.  

- 귀무가설 (H0) : $mu \ge 0$
- 대립가성 (H1) : $mu < 0$
- $\mu$ = (치료 후 혈압 - 치료 전 혈압) 의 평균
- $\alpha$ : 0.05  

1. $\mu$ 의 표본 평균은? (소수 둘째자리까지 반올림)
2. 검정통계량 값은? (소수 넷째자리까지 반올림)
3. p-값은? (소수 넷째자리까지 반올림)
4. 가설검정의 결과는? (유의수준 5%)

In [3]:
import pandas as pd 
from scipy import stats 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\high_blood_pressure.csv")

display(df.head(5))

     Id     sex  age  bp_pre  bp_post
0  p001    Male   33     149      129
1  p002    Male   39     168      168
2  p003    Male   70     176      155
3  p004  Female   41     169      178
4  p005    Male   48     160      126

In [4]:
df['diff'] = df['bp_post']-df['bp_pre']

print("mu 의 표본 평균")
print(round(df['diff'].mean(),2),"\n")

print("검정 통계량 값")
st, pv = stats.ttest_rel(df['bp_post'],df['bp_pre'],alternative="less")
print(round(st,4),"\n")

print("p-value")
print(round(pv,4),"\n")

if pv<=0.005 : 
    print("귀무가설 기각, 대립가설 채택")
else : 
    print("귀무가설 채택, 대립가설 기각")

mu 의 표본 평균
-6.12

검정 통계량 값
-3.0002

p-value
0.0016

귀무가설 기각, 대립가설 채택

stats.ttest_rel (t-검정, Paried t-test)  
- rel : Related 의 약자. 동일한 대상에 대해 어떠한 조치나 사건을 취하기 전과 후의 값을 비교할 때 사용함.  
- alternative="less" ==> 단측검정
    - 귀무가설 : 약을 먹기 전과 후의 혈압 차이가 없다
    - 대립가설 : 약을 먹은 후 혈압이 전보다 감소했다.

## T3-4 일원분산분석 (ANOVA)  

세 가지 다른 교육 방법(A, B, C)을 사용하여 수험생들의 시험 성적을 개선시키는 효과를 평가하고자 한다. 30명의 학생들을 무작위로 세 그룹으로 배정하여 교육을 실시하였고, 시험을 보고 성적을 측정하였습니다. 다음은 각 그룹의 학생들의 성적 데이터입니다.  

- 귀무가설(H0): 세 그룹(A, B, C) 간의 평균 성적 차이가 없다.
- 대립가설(H1 또는 Ha): 세 그룹(A, B, C) 간의 평균 성적 차이가 있다. 

다음 주어진 데이터로 일원배치법을 수행하여 그룹 간의 평균 성적 차이가 있는지 검정하세요
1. f값 (소수 둘째자리)
2. p값 (소수 여섯째자리)
3. 검정결과 출력

In [5]:
# 각 그룹의 데이터
groupA = [85, 92, 78, 88, 83, 90, 76, 84, 92, 87]
groupB = [79, 69, 84, 78, 79, 83, 79, 81, 86, 88]
groupC = [75, 68, 74, 65, 77, 72, 70, 73, 78, 75]

In [7]:
data = {'GroupA' : groupA, 'GroupB' : groupB, 'GroupC' : groupC}

df_wide = pd.DataFrame(data)
df_long = df_wide.melt(value_vars=['GroupA','GroupB','GroupC'],var_name='Group',value_name='Score')

f_value, p_value = stats.f_oneway(groupA,groupB,groupC)

print("F value : ",round(f_value,2))
print("P-value : {:.6f}".format(p_value))

F value :  16.88
P-value : 0.000018

In [8]:
display(df_wide.head(2))
display(df_long.head(2))

   GroupA  GroupB  GroupC
0      85      79      75
1      92      69      68

    Group  Score
0  GroupA     85
1  GroupA     92

df_long
- pd.melt 를 통해 독립변수 (Group) 과 종속변수 (Score) 를 표현 
- statsmodels 라이브러리로 ANOVA 테이블을 상세히 출력하거나 seaborn 으로 시각화할때 반드시 df_long 형태 데이터가 필수적임 

F-value  
- 집단 간의 차이가 유의한지 확인하는 통계량  
- $\frac{\text{집단 간 분산(Between-group Variance)}}{\text{집단 내 분산(Within-group Variance)}}$ = $\frac{\text{그룹 간 평균 제곱 (MSE)}}{\text{그룹 내 평균 제곱 (MSW)}}$
- 즉 SNR 이라고 보면 된다.

## T3-5 정규성 검정 (Shapiro-Wilks)
12명의 수험생이 빅데이터 분석기사 시험에서 받은 점수이다. Shapiro-Wilk 검정을 사용하여 데이터가 정규 분포를 따르는지 검증하시오
- 귀무 가설(H0): 데이터는 정규 분포를 따른다.
- 대립 가설(H1): 데이터는 정규 분포를 따르지 않는다. 

Shapiro-Wilk 검정 통계량, p-value, 검증결과를 출력하시오

In [11]:
from scipy import stats

data = [75, 83, 81, 92, 68, 77, 78, 80, 85, 95, 79, 89]

statistic, p_value = stats.shapiro(data)

print("Shapiro-Wilk 검정 통계량 : ",statistic)
print("p-value : ",p_value)


alpha=0.05
if p_value > alpha : 
    print("귀무 가설을 기각할 수 없다. 데이터는 정규분포를 따름")
else : 
    print("귀무가설을 기각한다. 데이터는 정규분포를 따르지 않음")

Shapiro-Wilk 검정 통계량 :  0.9768091723993144
p-value :  0.9676506711851194
귀무 가설을 기각할 수 없다. 데이터는 정규분포를 따름

Shapiro-Wilk 검정 
- 데이터가 가우시안 정규분포를 따르는지 확인하는 가설 검정 도구. 
- 샘플 수가 소표본일때 (3 ~ 50) 가장 높은 검정력 (Power) 를 보여주는 알고리즘  

- 실제 데이터의 분산 대비 정규분포라면 가졌어야 할 이상적인 변동성의 비율을 나타냄
    - $W=\frac{(\sum\limits^n_{i=1}a_i x_{(i)})^2}{\sum\limits^n_{i=1}(x_i-\bar{x})^2}$
    - 분모는 데이터 전체의 실제 편차 제곱합 (데이터 자체의 내재적 분산) 이고 분자는 데이터를 크기순으로 정렬한 값에 정규분포의 기대치로부터 유도된 특수한 가중치 계수를 내적하여 제곱한 값이다. 
    - W 통계량은 구조상 항상 0과 1 사이의 값을 가진다. 1에 가까울 경우 정규분포이다. 
    - 정규분포 Quantile 에 기반한 정규한 가중치 ($\alpha_i$) 를 사용하기 때문에 적은 데이터 안에서도 정규분포와의 미세한 편차를 잡아낸다. 그러나 데이터 수가 많아지면 지나치게 예민해진다.

- 가중치 $a_i$
    - 표준정규분포를 따르는 샘플들을 크기순으로 나열했을 때, 각 순서 (Rank) 가 가질것으로 기대되는 통계적 기댓값과 분산, 공분산 정보가 연산을 거쳐 상수로 치환되어 들어간다.

## T3-6 회귀모형 (상관계수)   

iris에서 Sepal Length와 Sepal Width의 상관계수 계산하고 소수 둘째자리까지 출력하시오

In [12]:
import pandas as pd
from sklearn.datasets import load_iris

# iris 데이터셋 로드
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
display(df.head(3))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [13]:
correlation = df.corr()
result = correlation.loc['sepal length (cm)','sepal width (cm)']
print(round(result,2))

-0.12

## T3-7 로지스틱 회귀  
Pclass, Gender, sibsp, parch를 독립변수로 사용하여 로지스틱 회귀모형을 실시하였을 때, parch변수의 계수값은? 단, Pclass는 범주형 변수이다 (반올림하여 소수 셋째 자리까지 계산)

In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\Titanic.csv")
display(df.head(3))

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
from statsmodels.formula.api import logit

# 모형의 물리적/통계적 관계식(수식) 정의
formula = "Survived ~ C(Pclass) + Gender + SibSp + Parch"

# 데이터를 모델에 주입하고, 최적의 파라미터를 찾도록 학습
model = logit(formula, data=df).fit()

# 학습이 완료된 후 각 변수의 계수만 뽑기
model.params

Optimization terminated successfully.
         Current function value: 0.459565
         Iterations 6

Intercept         2.491729
C(Pclass)[T.2]   -0.848152
C(Pclass)[T.3]   -1.866905
Gender[T.male]   -2.760281
SibSp            -0.232553
Parch            -0.049847
dtype: float64

- formula 
    - formula = "Survived ~ C(Pclass) + ... 를 다음과 같이 방정식을 세워달라고 하는것 
    - $y=\beta_0+\beta_1x_1+\beta_2x_+\dots$ 
    - ~ : 수학의 등호 = 역할
    - Survived : 최종적으로 예측하고싶은 종속변수 Y 의 열 이름
    - C(Pclass) + Gender + ... : 원인이 되는 독립변수 X 들의 열 이름 
    - \+ :이 변수도 방정식에 독립적인 항으로 추가 
    - C(항) : 범주형, Category
- logit
    - logit(formula, data=df).fit()
    - Coefficents 추출 : model.params['Parch'] 하여 찾기 
    - p-value 추출 : model.pvalues['변수 이름'] 하여 찾기

지금 구한 model.params 값들은 로그-오즈 공간 (Log-odds scale) 에서의 기울기 (Coefficient)  
$\ln({p\over 1-P})=\beta_0+\beta_1(\text{Pclass})+\beta_2(\text{Gender})+\dots$ 

로그를 사용하는 이유  
: 무한대로의 발산을 막기 위해서. Odds 는 실패 대비 성공의 확률 비율 $\text{Odds}={P\over 1-P}$ 를 의미하는데 이를 통해서 (0,1) 로 제어할 수 있다.

## T3-8 두 그룹 평균비교 (T/F 검정)  
문제: 두 교육 방법의 효과 비교  
연구자는 두 가지 다른 교육 방법이 학생들의 성적에 미치는 영향을 비교하고자 합니다. 연구자는 무작위로 선발된 20명의 학생들을 두 그룹으로 나누어 한 그룹에는 교육 방법 A를, 다른 그룹에는 교육 방법 B를 적용합니다. 교육이 끝난 후, 두 그룹의 성적을 비교하기 위해 독립 표본 t-검정과 ANOVA F-검정을 실시하려고 합니다.

다음은 두 그룹의 성적입니다: 다음의 두 가지 검정을 사용하여 두 교육 방법 간의 성적 차이가 통계적으로 유의한지를 검증하세요

1. 독립 표본 t-검정을 실시하여 t 통계량을 구하세요.
2. 독립 표본 t-검정을 실시하여 p-값을 구하세요.
3. ANOVA F-검정을 실시하여 F 통계량을 구하세요.
4. ANOVA F-검정을 실시하여 p-값을 구하세요.

In [7]:
import pandas as pd
df = pd.DataFrame({
    'A':[77, 75, 82, 80, 81, 83, 84, 76, 75, 87],
    'B':[80, 74, 77, 79, 71, 74, 78, 69, 70, 72],
})

from scipy import stats 
print("독립표본")
print(stats.ttest_ind(df['A'],df['B']))
print("\n")
# ANOVA F-검정 
print("ANOVA F-검정")
print(stats.f_oneway(df['A'],df['B']))

독립표본
TtestResult(statistic=np.float64(3.1068522301122954), pvalue=np.float64(0.006087373605949964), df=np.float64(18.0))


ANOVA F-검정
F_onewayResult(statistic=np.float64(9.652530779753766), pvalue=np.float64(0.0060873736059499145))

In [8]:
# 좀 더 예쁘게 
t_res = stats.ttest_ind(df['A'],df['B'])
f_res = stats.f_oneway(df['A'],df['B'])

print("=" * 45)
print(f"{'분석 유형':<15} | {'검정 통계량':<10} | {'p-value':<10}")
print("-" * 45)
print(f"{'독립표본 t-검정':<11} | {t_res.statistic:>11.4f} | {t_res.pvalue:>10.4f}")
print(f"{'일원분산분석(ANOVA)':<10} | {f_res.statistic:>11.4f} | {f_res.pvalue:>10.4f}")
print("=" * 45)

=============================================
분석 유형           | 검정 통계량     | p-value
---------------------------------------------
독립표본 t-검정   |      3.1069 |     0.0061
일원분산분석(ANOVA) |      9.6525 |     0.0061
=============================================

## T3-9 적합도 검정 (Chi-square)  
카이제곱 적합도 검정  

고등학교에서는 졸업생들이 선택하는 대학 전공 분야의 선호도가 시간이 지남에 따라 변하지 않는다고 가정합니다. 학교 측은 최근 졸업생들의 전공 선택이 과거와 같은 패턴을 따르는지 알아보기 위해 적합도 검정을 실시하기로 결정했습니다.

과거 자료에 따르면 졸업생들이 선택하는 전공의 분포는 다음과 같습니다:

인문학: 20% 사회과학: 30% 자연과학: 25% 공학: 15% 기타: 10% 올해 졸업한 학생 200명의 전공 선택 분포는 다음과 같았습니다:

인문학: 30명 사회과학: 60명 자연과학: 50명 공학: 40명 기타: 20명 이 데이터를 바탕으로, 졸업생들의 전공 선택 패턴이 과거와 유사한지를 알아보기 위해 카이제곱 적합도 검정을 실시해야 합니다. 유의 수준은 0.05로 설정합니다.

1. 검정통계량 구하라
2. p-value 를 구하가
3. 유의수준 하 귀무가설 기각 또는 채택?

In [13]:
from scipy.stats import chisquare

# 관측된 빈도
observed_frequencies = [30, 60, 50, 40, 20]

# 기대된 빈도 
expected_frequencies = [200 * 0.20, 200 * 0.30, 200 * 0.25, 200 * 0.15, 200 * 0.10]

# 카이제곱 검정
# 카이제곱 검정
chi = chisquare(f_obs=observed_frequencies, f_exp=expected_frequencies)
statistic = chi.statistic
p_value = chi.pvalue 

print("검정통계량 : ",statistic)
print("p-value : ",p_value)
if p_value < 0.05 : 
    print("대립가설 채택")
else : 
    print("귀무가설 채택")

검정통계량 :  5.833333333333334
p-value :  0.21194558437271782
귀무가설 채택

## T3-10 지지도/신뢰도/향상도  
지지도, 신뢰도, 향상도  

1. '빼빼로'와 '딴짓초코'가 함께 팔린 거래의 지지도를 계산하세요.
2. '빼빼로'가 팔린 거래 중에서 '빼빼로'와 '오징어칩'이 함께 팔린 거래의 신뢰도를 계산하세요.
3. '빼빼로'와 '양조위빵'의 향상도를 계산하세요. 

- 지지도(A,B): A와 B가 함께 팔린 거래 횟수 / 전체 거래 횟수 
- 신뢰도(A->B): A와 B가 함께 팔린 거래 횟수 / A가 팔린 거래 횟수
- 향상도(A,B): 신뢰도(A->B) / 지지도(B)

In [14]:
import pandas as pd
# 데이터
df = pd.DataFrame({
    'transaction': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    '빼빼로': [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
    '딴짓초코': [0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
    '양조위빵': [1, 0, 0, 1, 1, 1, 0, 0, 1, 0],
    '오징어칩': [0, 1, 1, 0, 0, 1, 0, 1, 1, 1],
    '초코파이': [1, 1, 0, 0, 1, 0, 1, 1, 0, 0]
})
df

   transaction  빼빼로  딴짓초코  양조위빵  오징어칩  초코파이
0            1    1     0     1     0     1
1            2    0     1     0     1     1
2            3    1     1     0     1     0
3            4    1     0     1     0     0
4            5    0     1     1     0     1
5            6    1     0     1     1     0
6            7    1     1     0     0     1
7            8    0     1     0     1     1
8            9    1     0     1     1     0
9           10    1     0     0     1     0

In [ ]:
# 각 문제의 계산을 위한 데이터 준비
total = df.shape[0]
pepero = df['빼빼로'].sum()

# 문제 1 : 빼빼로와 딴짓초코가 함께 팔린 거래의 지지도

## T3-11 포아송분포