## T3-1 단일표본 T 검정

다음은 22명의 학생들이 국어시험에서 받은 점수이다. 학생들의 평균이 75보다 크다고 할 수 있는가?  
$H_0$ : 모평균은 $\mu$ 와 같다. 학생들의 평균은 75이다.  
$H_1$ : 모평균은 $\mu$ 가 아니다. 학생들의 평균은 75보다 크다.  

가정  
1. 모집단은 정규분포를 따른다.  
2. 표본의 크기가 충분히 크다.  

검정통계량, p-value, 검정결과를 출력하시오

In [1]:
from scipy.stats import ttest_1samp

# 데이터 
scores = [75, 80, 68, 72, 77, 82, 81, 79, 70, 74, 76, 78, 81, 73, 81, 78, 75, 72, 74, 79, 78, 79]

# 모평균 가설검정
mu = 75 # 모평균
alpha = 0.05 # 유의수준

# t-test 를 사용하여 가설 검정
t_statistic, p_value = ttest_1samp(scores, mu, alternative='greater')

print("t-statistic : ",t_statistic)
print("p-value : ",p_value)

if p_value < alpha : 
    print("귀무가설을 기각합니다. 모평균은 75보다 큽니다.")
else :
    print("귀무가설을 채택합니다. 모평균은 75보다 크지 않습니다.")

t-statistic :  1.765879233231226
p-value :  0.04597614747709138
귀무가설을 기각합니다. 모평균은 75보다 큽니다.

ttest_1samp (일표본 t-검정, One-sample t-test)  

- 하나의 표본 집단의 평균이 연구자가 가정한 특정 이론값과 통계적으로 같을지 다를지 검정  
- stats.stats.ttest_1samp(데이터 배열, popmean = 기준값) 
- 자유도 n-1

## T3-2 독립표본 T검정  
어떤 특정 약물을 복용한 사람들의 평균 체온이 복용하지 않은 사람들의 평균 체온과 유의미하게 다른지 검정해보려고 합니다.  

가정 : 
- 약물을 복용한 그룹과 복용하지 않은 그룹의 체온 데이터가 각각 주어져 있다고 가정합니다.
- 각 그룹의 체온은 정규분포를 따른다고 가정합니다.  

검정통계량, p-value, 검정결과를 출력하시오

In [2]:
from scipy import stats 

# 데이터 수집
group1 = [36.8, 36.7, 37.1, 36.9, 37.2, 36.8, 36.9, 37.1, 36.7, 37.1]
group2 = [36.5, 36.6, 36.3, 36.6, 36.9, 36.7, 36.7, 36.8, 36.5, 36.7]

t_statistics, p_value = stats.ttest_ind(group1, group2)

print("검정통계량 : ",t_statistics)
print("p-value : ",p_value)

alpha=0.05

if p_value < alpha:
    print("귀무가설을 기각합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 있습니다.")
else:
    print("귀무가설을 채택합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 없습니다.")

검정통계량 :  3.7964208654863336
p-value :  0.0013218914767036936
귀무가설을 기각합니다. 약물을 복용한 그룹과 복용하지 않은 그룹의 평균 체온은 유의미한 차이가 있습니다.

stats.ttest_ind (독립표본 t-검정, Independent two-sample t-test)
- 서로 상관이 없는 독립된 두 표본 집단의 평균을 비교하여, 두 모집단의 평균이 같은지 다른지 검정  
- stats.ttest_ind(표본1, 표본2, equal_val=True) 
    - 두 집단의 분산이 같은지 모를 때는 equal_var=False 를 주어 웰치의 t-검정 (Welch's t-test) 를 수행하는것이 더 안전
- 자유도 $n_1+n_2-2$ (등분산 가정시)

## T3-3 대응표본 T검정  

주어진 데이터는 고혈압 환자 치료 전후의 혈압이다.  
해당 치료가 효과가 있는지 대응 (쌍체) 표본 t-검정을 진행하시오.  

- 귀무가설 (H0) : $mu \ge 0$
- 대립가성 (H1) : $mu < 0$
- $\mu$ = (치료 후 혈압 - 치료 전 혈압) 의 평균
- $\alpha$ : 0.05  

1. $\mu$ 의 표본 평균은? (소수 둘째자리까지 반올림)
2. 검정통계량 값은? (소수 넷째자리까지 반올림)
3. p-값은? (소수 넷째자리까지 반올림)
4. 가설검정의 결과는? (유의수준 5%)

In [3]:
import pandas as pd 
from scipy import stats 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\high_blood_pressure.csv")

display(df.head(5))

     Id     sex  age  bp_pre  bp_post
0  p001    Male   33     149      129
1  p002    Male   39     168      168
2  p003    Male   70     176      155
3  p004  Female   41     169      178
4  p005    Male   48     160      126

In [4]:
df['diff'] = df['bp_post']-df['bp_pre']

print("mu 의 표본 평균")
print(round(df['diff'].mean(),2),"\n")

print("검정 통계량 값")
st, pv = stats.ttest_rel(df['bp_post'],df['bp_pre'],alternative="less")
print(round(st,4),"\n")

print("p-value")
print(round(pv,4),"\n")

if pv<=0.005 : 
    print("귀무가설 기각, 대립가설 채택")
else : 
    print("귀무가설 채택, 대립가설 기각")

mu 의 표본 평균
-6.12

검정 통계량 값
-3.0002

p-value
0.0016

귀무가설 기각, 대립가설 채택

stats.ttest_rel (t-검정, Paried t-test)  
- rel : Related 의 약자. 동일한 대상에 대해 어떠한 조치나 사건을 취하기 전과 후의 값을 비교할 때 사용함.  
- alternative="less" ==> 단측검정
    - 귀무가설 : 약을 먹기 전과 후의 혈압 차이가 없다
    - 대립가설 : 약을 먹은 후 혈압이 전보다 감소했다.

## T3-4 일원분산분석 (ANOVA)  

세 가지 다른 교육 방법(A, B, C)을 사용하여 수험생들의 시험 성적을 개선시키는 효과를 평가하고자 한다. 30명의 학생들을 무작위로 세 그룹으로 배정하여 교육을 실시하였고, 시험을 보고 성적을 측정하였습니다. 다음은 각 그룹의 학생들의 성적 데이터입니다.  

- 귀무가설(H0): 세 그룹(A, B, C) 간의 평균 성적 차이가 없다.
- 대립가설(H1 또는 Ha): 세 그룹(A, B, C) 간의 평균 성적 차이가 있다. 

다음 주어진 데이터로 일원배치법을 수행하여 그룹 간의 평균 성적 차이가 있는지 검정하세요
1. f값 (소수 둘째자리)
2. p값 (소수 여섯째자리)
3. 검정결과 출력

In [5]:
# 각 그룹의 데이터
groupA = [85, 92, 78, 88, 83, 90, 76, 84, 92, 87]
groupB = [79, 69, 84, 78, 79, 83, 79, 81, 86, 88]
groupC = [75, 68, 74, 65, 77, 72, 70, 73, 78, 75]

In [6]:
data = {'GroupA' : groupA, 'GroupB' : groupB, 'GroupC' : groupC}

df_wide = pd.DataFrame(data)
df_long = df_wide.melt(value_vars=['GroupA','GroupB','GroupC'],var_name='Group',value_name='Score')

f_value, p_value = stats.f_oneway(groupA,groupB,groupC)

print("F value : ",round(f_value,2))
print("P-value : {:.6f}".format(p_value))

F value :  16.88
P-value : 0.000018

In [7]:
display(df_wide.head(2))
display(df_long.head(2))

   GroupA  GroupB  GroupC
0      85      79      75
1      92      69      68

    Group  Score
0  GroupA     85
1  GroupA     92

df_long
- pd.melt 를 통해 독립변수 (Group) 과 종속변수 (Score) 를 표현 
- statsmodels 라이브러리로 ANOVA 테이블을 상세히 출력하거나 seaborn 으로 시각화할때 반드시 df_long 형태 데이터가 필수적임 

F-value  
- 집단 간의 차이가 유의한지 확인하는 통계량  
- $\frac{\text{집단 간 분산(Between-group Variance)}}{\text{집단 내 분산(Within-group Variance)}}$ = $\frac{\text{그룹 간 평균 제곱 (MSE)}}{\text{그룹 내 평균 제곱 (MSW)}}$
- 즉 SNR 이라고 보면 된다.

## T3-5 정규성 검정 (Shapiro-Wilks)
12명의 수험생이 빅데이터 분석기사 시험에서 받은 점수이다. Shapiro-Wilk 검정을 사용하여 데이터가 정규 분포를 따르는지 검증하시오
- 귀무 가설(H0): 데이터는 정규 분포를 따른다.
- 대립 가설(H1): 데이터는 정규 분포를 따르지 않는다. 

Shapiro-Wilk 검정 통계량, p-value, 검증결과를 출력하시오

In [8]:
from scipy import stats

data = [75, 83, 81, 92, 68, 77, 78, 80, 85, 95, 79, 89]

statistic, p_value = stats.shapiro(data)

print("Shapiro-Wilk 검정 통계량 : ",statistic)
print("p-value : ",p_value)


alpha=0.05
if p_value > alpha : 
    print("귀무 가설을 기각할 수 없다. 데이터는 정규분포를 따름")
else : 
    print("귀무가설을 기각한다. 데이터는 정규분포를 따르지 않음")

Shapiro-Wilk 검정 통계량 :  0.9768091723993144
p-value :  0.9676506711851194
귀무 가설을 기각할 수 없다. 데이터는 정규분포를 따름

Shapiro-Wilk 검정 
- 데이터가 가우시안 정규분포를 따르는지 확인하는 가설 검정 도구. 
- 샘플 수가 소표본일때 (3 ~ 50) 가장 높은 검정력 (Power) 를 보여주는 알고리즘  

- 실제 데이터의 분산 대비 정규분포라면 가졌어야 할 이상적인 변동성의 비율을 나타냄
    - $W=\frac{(\sum\limits^n_{i=1}a_i x_{(i)})^2}{\sum\limits^n_{i=1}(x_i-\bar{x})^2}$
    - 분모는 데이터 전체의 실제 편차 제곱합 (데이터 자체의 내재적 분산) 이고 분자는 데이터를 크기순으로 정렬한 값에 정규분포의 기대치로부터 유도된 특수한 가중치 계수를 내적하여 제곱한 값이다. 
    - W 통계량은 구조상 항상 0과 1 사이의 값을 가진다. 1에 가까울 경우 정규분포이다. 
    - 정규분포 Quantile 에 기반한 정규한 가중치 ($\alpha_i$) 를 사용하기 때문에 적은 데이터 안에서도 정규분포와의 미세한 편차를 잡아낸다. 그러나 데이터 수가 많아지면 지나치게 예민해진다.

- 가중치 $a_i$
    - 표준정규분포를 따르는 샘플들을 크기순으로 나열했을 때, 각 순서 (Rank) 가 가질것으로 기대되는 통계적 기댓값과 분산, 공분산 정보가 연산을 거쳐 상수로 치환되어 들어간다.

## T3-6 회귀모형 (상관계수)   

iris에서 Sepal Length와 Sepal Width의 상관계수 계산하고 소수 둘째자리까지 출력하시오

In [9]:
import pandas as pd
from sklearn.datasets import load_iris

# iris 데이터셋 로드
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
display(df.head(3))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [10]:
correlation = df.corr()
result = correlation.loc['sepal length (cm)','sepal width (cm)']
print(round(result,2))

-0.12

## T3-7 로지스틱 회귀  
Pclass, Gender, sibsp, parch를 독립변수로 사용하여 로지스틱 회귀모형을 실시하였을 때, parch변수의 계수값은? 단, Pclass는 범주형 변수이다 (반올림하여 소수 셋째 자리까지 계산)

In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\Titanic.csv")
display(df.head(3))

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [12]:
from statsmodels.formula.api import logit

# 모형의 물리적/통계적 관계식(수식) 정의
formula = "Survived ~ C(Pclass) + Gender + SibSp + Parch"

# 데이터를 모델에 주입하고, 최적의 파라미터를 찾도록 학습
model = logit(formula, data=df).fit()

# 학습이 완료된 후 각 변수의 계수만 뽑기
model.params

Optimization terminated successfully.
         Current function value: 0.459565
         Iterations 6

Intercept         2.491729
C(Pclass)[T.2]   -0.848152
C(Pclass)[T.3]   -1.866905
Gender[T.male]   -2.760281
SibSp            -0.232553
Parch            -0.049847
dtype: float64

- formula 
    - formula = "Survived ~ C(Pclass) + ... 를 다음과 같이 방정식을 세워달라고 하는것 
    - $y=\beta_0+\beta_1x_1+\beta_2x_+\dots$ 
    - ~ : 수학의 등호 = 역할
    - Survived : 최종적으로 예측하고싶은 종속변수 Y 의 열 이름
    - C(Pclass) + Gender + ... : 원인이 되는 독립변수 X 들의 열 이름 
    - \+ :이 변수도 방정식에 독립적인 항으로 추가 
    - C(항) : 범주형, Category
- logit
    - logit(formula, data=df).fit()
    - Coefficents 추출 : model.params['Parch'] 하여 찾기 
    - p-value 추출 : model.pvalues['변수 이름'] 하여 찾기

지금 구한 model.params 값들은 로그-오즈 공간 (Log-odds scale) 에서의 기울기 (Coefficient)  
$\ln({p\over 1-P})=\beta_0+\beta_1(\text{Pclass})+\beta_2(\text{Gender})+\dots$ 

로그를 사용하는 이유  
: 무한대로의 발산을 막기 위해서. Odds 는 실패 대비 성공의 확률 비율 $\text{Odds}={P\over 1-P}$ 를 의미하는데 이를 통해서 (0,1) 로 제어할 수 있다.

## T3-8 두 그룹 평균비교 (T/F 검정)  
문제: 두 교육 방법의 효과 비교  
연구자는 두 가지 다른 교육 방법이 학생들의 성적에 미치는 영향을 비교하고자 합니다. 연구자는 무작위로 선발된 20명의 학생들을 두 그룹으로 나누어 한 그룹에는 교육 방법 A를, 다른 그룹에는 교육 방법 B를 적용합니다. 교육이 끝난 후, 두 그룹의 성적을 비교하기 위해 독립 표본 t-검정과 ANOVA F-검정을 실시하려고 합니다.

다음은 두 그룹의 성적입니다: 다음의 두 가지 검정을 사용하여 두 교육 방법 간의 성적 차이가 통계적으로 유의한지를 검증하세요

1. 독립 표본 t-검정을 실시하여 t 통계량을 구하세요.
2. 독립 표본 t-검정을 실시하여 p-값을 구하세요.
3. ANOVA F-검정을 실시하여 F 통계량을 구하세요.
4. ANOVA F-검정을 실시하여 p-값을 구하세요.

In [13]:
import pandas as pd
df = pd.DataFrame({
    'A':[77, 75, 82, 80, 81, 83, 84, 76, 75, 87],
    'B':[80, 74, 77, 79, 71, 74, 78, 69, 70, 72],
})

from scipy import stats 
print("독립표본")
print(stats.ttest_ind(df['A'],df['B']))
print("\n")
# ANOVA F-검정 
print("ANOVA F-검정")
print(stats.f_oneway(df['A'],df['B']))

독립표본
TtestResult(statistic=np.float64(3.1068522301122954), pvalue=np.float64(0.006087373605949964), df=np.float64(18.0))


ANOVA F-검정
F_onewayResult(statistic=np.float64(9.652530779753766), pvalue=np.float64(0.0060873736059499145))

In [14]:
# 좀 더 예쁘게 
t_res = stats.ttest_ind(df['A'],df['B'])
f_res = stats.f_oneway(df['A'],df['B'])

print("=" * 45)
print(f"{'분석 유형':<15} | {'검정 통계량':<10} | {'p-value':<10}")
print("-" * 45)
print(f"{'독립표본 t-검정':<11} | {t_res.statistic:>11.4f} | {t_res.pvalue:>10.4f}")
print(f"{'일원분산분석(ANOVA)':<10} | {f_res.statistic:>11.4f} | {f_res.pvalue:>10.4f}")
print("=" * 45)

=============================================
분석 유형           | 검정 통계량     | p-value
---------------------------------------------
독립표본 t-검정   |      3.1069 |     0.0061
일원분산분석(ANOVA) |      9.6525 |     0.0061
=============================================

## T3-9 적합도 검정 (Chi-square)  
카이제곱 적합도 검정  

고등학교에서는 졸업생들이 선택하는 대학 전공 분야의 선호도가 시간이 지남에 따라 변하지 않는다고 가정합니다. 학교 측은 최근 졸업생들의 전공 선택이 과거와 같은 패턴을 따르는지 알아보기 위해 적합도 검정을 실시하기로 결정했습니다.

과거 자료에 따르면 졸업생들이 선택하는 전공의 분포는 다음과 같습니다:

인문학: 20% 사회과학: 30% 자연과학: 25% 공학: 15% 기타: 10% 올해 졸업한 학생 200명의 전공 선택 분포는 다음과 같았습니다:

인문학: 30명 사회과학: 60명 자연과학: 50명 공학: 40명 기타: 20명 이 데이터를 바탕으로, 졸업생들의 전공 선택 패턴이 과거와 유사한지를 알아보기 위해 카이제곱 적합도 검정을 실시해야 합니다. 유의 수준은 0.05로 설정합니다.

1. 검정통계량 구하라
2. p-value 를 구하가
3. 유의수준 하 귀무가설 기각 또는 채택?

In [15]:
from scipy.stats import chisquare

# 관측된 빈도
observed_frequencies = [30, 60, 50, 40, 20]

# 기대된 빈도 
expected_frequencies = [200 * 0.20, 200 * 0.30, 200 * 0.25, 200 * 0.15, 200 * 0.10]

# 카이제곱 검정
# 카이제곱 검정
chi = chisquare(f_obs=observed_frequencies, f_exp=expected_frequencies)
statistic = chi.statistic
p_value = chi.pvalue 

print("검정통계량 : ",statistic)
print("p-value : ",p_value)
if p_value < 0.05 : 
    print("대립가설 채택")
else : 
    print("귀무가설 채택")

검정통계량 :  5.833333333333334
p-value :  0.21194558437271782
귀무가설 채택

## T3-10 지지도/신뢰도/향상도  
지지도, 신뢰도, 향상도  

1. '빼빼로'와 '딴짓초코'가 함께 팔린 거래의 지지도를 계산하세요.
2. '빼빼로'가 팔린 거래 중에서 '빼빼로'와 '오징어칩'이 함께 팔린 거래의 신뢰도를 계산하세요.
3. '빼빼로'와 '양조위빵'의 향상도를 계산하세요. 

- 지지도(A,B): A와 B가 함께 팔린 거래 횟수 / 전체 거래 횟수 
- 신뢰도(A->B): A와 B가 함께 팔린 거래 횟수 / A가 팔린 거래 횟수
- 향상도(A,B): 신뢰도(A->B) / 지지도(B)

In [16]:
import pandas as pd
# 데이터
df = pd.DataFrame({
    'transaction': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    '빼빼로': [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
    '딴짓초코': [0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
    '양조위빵': [1, 0, 0, 1, 1, 1, 0, 0, 1, 0],
    '오징어칩': [0, 1, 1, 0, 0, 1, 0, 1, 1, 1],
    '초코파이': [1, 1, 0, 0, 1, 0, 1, 1, 0, 0]
})
df

   transaction  빼빼로  딴짓초코  양조위빵  오징어칩  초코파이
0            1    1     0     1     0     1
1            2    0     1     0     1     1
2            3    1     1     0     1     0
3            4    1     0     1     0     0
4            5    0     1     1     0     1
5            6    1     0     1     1     0
6            7    1     1     0     0     1
7            8    0     1     0     1     1
8            9    1     0     1     1     0
9           10    1     0     0     1     0

In [19]:
# 각 문제의 계산을 위한 데이터 준비
total = df.shape[0]
pepero = df['빼빼로'].sum()

# 문제 1 : 빼빼로와 딴짓초코가 함께 팔린 거래의 지지도 
pepero_and_choco = len(df[(df["빼빼로"]==1)&(df["딴짓초코"]==1)])
print("빼빼로와 딴짓 초코가 함께 팔린 거래의 지지도 : ",pepero_and_choco/total*100)

# 문제 2 : 빼빼로가 팔린 거래 중 빼빼로와 오징어칩이 함께 팔린 거래의 신뢰도 
pepero_and_squid = len(df[(df["빼빼로"]==1)&(df["오징어칩"]==1)])
print("뻬빼로가 팔린 거래 중 빼빼로와 오징어칩이 함께 팔린 거래의 신뢰도 : ",pepero_and_squid/pepero*100)

# 빼빼로와 양조위빵의 향상도
pepero_and_bread = len(df[(df["빼빼로"]==1)&(df["양조위빵"]==1)])
bread=df["양조위빵"].sum()
print("빼빼로와 양조위빵의 향상도 : ",(pepero_and_bread/pepero)/(bread/total)*100)

빼빼로와 딴짓 초코가 함께 팔린 거래의 지지도 :  20.0
뻬빼로가 팔린 거래 중 빼빼로와 오징어칩이 함께 팔린 거래의 신뢰도 :  57.14285714285714
빼빼로와 양조위빵의 향상도 :  114.28571428571428

지지도 
- $P(A\cap B)={\text{항목 A와 항목 B를 동시에 포함하는 거래}\over \text{전체 거래 수}}$ 

신뢰도 : 항목 A 를 포함하는 거래 중에서 항목 B 도 함께 포함되어 있을 확률 
- $P(B|A) = \frac{\text{항목 A와 항목 B를 동시에 포함하는 거래 수}}{\text{항목 A를 포함하는 거래 수}}$

향상도 : 항목 A 를 구매하지 않았을 때를 비교하여 B 의 구매확률이 얼마나 상승했는지 나타내는 지표
- $\frac{P(B|A)}{P(B)}=\frac{P(A\cap B)}{P(A)\times P(B)}=\frac{\text{Confidence}(A\rightarrow B)}{P(B)}$
- Lift > 1 : 양의 상관관계. 상호 보완재 효과. A 를 사면 B 를 살 확률이 그냥 살 때보다 높아짐
- Lift = 1 : 독립관계
- Lift < 1 : 음의 상관관계

## T3-11 포아송분포  
문제: 한 서점에서는 평균적으로 하루에 3명의 고객이 특정 잡지를 구매합니다. 이 데이터는 포아송 분포를 따른다고 가정할 때, 다음 질문에 대한 답을 구하세요. 

- 하루에 정확히 5명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오)
- 하루에 적어도 2명의 고객이 잡지를 구매할 확률은 얼마입니까? (%로 값을 정수로 입력하시오) 
- 포아송 분포의 PMF 
    - $P(X=k)=\frac{e^{-\lambda}\lambda^k}{k!}$

In [24]:
from scipy.stats import poisson

lambda_3 = 3 # 평균 발생 횟수
print("하루에 정확히 5명의 고객이 잡지를 구매할 확률 : ",int(poisson.pmf(5,lambda_3)*100),"%")
print("하루에 적어도 2 명의 고객이 잡지를 구매할 확률 : ",int((1-poisson.cdf(1,lambda_3))*100),"%")

하루에 정확히 5명의 고객이 잡지를 구매할 확률 :  10 %
하루에 적어도 2 명의 고객이 잡지를 구매할 확률 :  80 %

## T3-12 독립성 검정 (교차표)  

성별과 시험합격은 독립적인가를 검정하시오  
1. 검정 통계량
2. p-value
3. 귀무가설 기준 (기각/채택)
4. 남자의 합격 기대 빈도

In [25]:
import pandas as pd
from scipy import stats

# 데이터 프레임 생성
df = pd.DataFrame({'남자': [100, 200],
                   '여자': [130, 170]},
                  index=['합격', '불합격'])

In [26]:
# 카이제곱 검정 수행
statistic, pvalue, dof, expected = stats.chi2_contingency(df)

print(f"검정통계량 : {statistic}")
print(f"p-value : {pvalue}")
print(expected)
print(f"남자의 합격 기대빈도 : {expected[0][0]}")

검정통계량 : 5.929494712103407
p-value : 0.01488951060599475
[[115. 115.]
 [185. 185.]]
남자의 합격 기대빈도 : 115.0

기대빈도 (expected frequency) : 귀무 가설 하에서 관찰될 것으로 예상되는 빈도. 
귀무가설은 일반적으로 두 변수가 서로 독립적이라고 주장한다.

## T3-13 베르누이/이항분포
- [베르누이 분포] 다음 데이터는 100번의 시도에서 각각 성공(1) 또는 실패(0)를 나타냅니다. 이 데이터를 바탕으로 각 시도의 성공 확률을 계산하시오.  

- [이항분포] 1번 문제에서 계산한 성공 확률을 사용하여, 100번의 시도 중 정확히 60번 성공할 확률을 계산하시오.

In [27]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\t3_success.csv")
display(df)

    Success
0         1
1         0
2         0
3         1
4         1
..      ...
95        1
96        1
97        1
98        0
99        1

[100 rows x 1 columns]

In [28]:
# 베르누이 분포 : 각 시도의 성공 확률 계산
total_attempts = len(df)
number_of_successes = df['Success'].sum()
success_probability = number_of_successes / total_attempts 
print(success_probability)

0.62

In [29]:
# 이항 분포 
from scipy.stats import binom
n, k = 100, 60 
probability_of_60_successes = binom.pmf(k,n,success_probability)
print(probability_of_60_successes)

0.07464985555860273

## T3-14 점추정/구간추정 
데이터셋은 어떤 도시의 일일 평균 온도 입니다. 
- 점추정: 데이터셋을 기반으로 이 도시의 평균 연간 온도를 점추정하세요. (반올림하여 소수 둘째자리까지) 
- 구간추정: 95% 신뢰수준에서 이 도시의 평균 연간 온도에 대한 신뢰구간을 구하세요. (반올림하여 소수 둘째자리까지)

In [30]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\daily_temperatures.csv")
display(df.head(5))

   Daily Average Temperature
0                  28.820262
1                  22.000786
2                  24.893690
3                  31.204466
4                  29.337790

In [31]:
# 점추정 : 샘플 평균 계산
from scipy import stats 

sample_mean = df['Daily Average Temperature'].mean()

# 구간 추정 : 샘플 표준편차 계산 및 신뢰구간 계산
confidence_level = 0.95
sample_std = df['Daily Average Temperature'].std() # 자유도 n-1 로 설정
n_samples = len(df)

# 95% 신뢰구간 계산
confidence_interval = stats.t.interval(confidence_level,df=n_samples-1, loc=sample_mean, scale=sample_std/(n_samples**0.5))

print("평균 : ",sample_mean)
print("Confidence interval : ",confidence_interval)

평균 :  19.937577543978538
Confidence interval :  (np.float64(19.427887094620374), np.float64(20.447267993336702))

점추정 (Point Estimation) 
- 모집단의 모수가 딱 이 값일 것이다라고 하나의 수치로 추정하는 방법

## T3-15 이원분산분석 (Two-way ANOVA)  
크리스마스 장식 종류와 지역에 따라 판매량에 유의미한 차이가 있는지 이원 분산 분석을 통해 검정하세요  
1. 크리스마스 장식 종류(트리, 조명, 장식품)가 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오 
2. 지역(북부, 남부, 동부, 서부)이 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오 
3. 크리스마스 장식 종류와 지역의 상호작용이 판매량에 미치는 영향을 분석하세요. 이때, 장식 종류의 F-value, p-value를 구하시오

In [33]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\christmas_decoration_sales.csv")
display(df.head(3))

  Decoration_Type Region  Sales
0              트리     북부     64
1              트리     남부     67
2              트리     동부     84

In [34]:
# 이원 분산 분석
import statsmodels.api as sm 
from statsmodels.formula.api import ols 

model = ols('Sales ~ C(Decoration_Type) * C(Region)',data=df).fit()
sm.stats.anova_lm(model)

,df,sum_sq,mean_sq,F,PR(>F)
C(Decoration_Type),2.0,1764.500000,882.250000,2.370578,0.114943
C(Region),3.0,804.305556,268.101852,0.720381,0.549614
C(Decoration_Type):C(Region),6.0,5153.944444,858.990741,2.308081,0.066915
Residual,24.0,8932.000000,372.166667,NaN,NaN

statsmodels.formula.api 
- Ordinary Least Squares(최소제곱법) 의 약자로, 선형 모델을 정의하고 데이터로부터 파라미터 (계수) 를 추정하는 엔진 
- R-style formula 를 파이썬 문자열 형태로 받아 Design Matrix 로 변환
- .fit() => 오차의 제곱합을 최소화하는 전통적인 선형 회귀 최적화 수식을 풀어내여 '학습된 모델 객체' 를 반환  

statsmodels.api 
- 모델 학습 이후 이를 바탕으로 각종 가설 검정, 잔차 분석, 통계 리포트 생성

## T3-16 로지스틱 회귀 2단계 
고객 정보를 나타낸 데이터이다. 주어진 데이터에서 500개 중 앞에서부터 350개는 train으로, 150개는 test 데이터로 나눈다. 모델을 학습(적합)할 때는 train 데이터를 사용하고, 예측할 때는 test 데이터를 사용한다. 모델은 로지스틱 회귀를 써서 고객이 특정 제품을 구매할지 여부를 예측하되, 페널티는 부과하지 않는다. 

문제 1-1. income 변수를 독립변수로 purchase를 종속변수로 사용하여 로지스틱 회귀 모형을 만들고, income 변수가 한 단위 증가할 때 구매할 오즈비 값을 계산하시오. (반올림하여 소수 넷째자리까지 계산)  

문제 1-2. 독립변수 income만 사용해 학습한 모델에서 test 데이터의 purchase를 예측하고, accuracy (정확도)를 구하시오. (반올림하여 소수 셋째자리까지 계산)  

문제 1-3. 독립변수 income만 사용해 학습한 모델의 로짓 우도를 계산하시오.  

문제 1-4. 독립변수 income만 사용해 학습한 모델의 유의확률(p-value)를 구하시오

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\Customer_Data.csv")
display(df.head(3))

   age  income  marital_status  children  gender  purchase
0   62  111980               1         2       1         0
1   65  107314               0         3       1         0
2   18   56209               1         1       1         1

In [ ]:
from statsmodels.formula.api import logit 
import numpy as np 

# 데이터셋 분할
train = df.iloc[:350]
test = df.iloc[350:]
## train_test_split 으로 가르면 랜덤으로 갈리기때문에 시계열 데이터에서 사용하면 안된다.
## 그러나 여기서는 그냥 리스트 숫자로 갈라버린 듯 

# 문제 1-1: income 변수를 독립변수로 purchase를 종속변수로 사용하여 로지스틱 회귀 모형을 만들고, 
# income 변수가 한 단위 증가할 때 구매할 오즈비 값을 계산
model_income = logit('purchase ~ income',data=train)
result_income = model_income.fit()
'''
변수의 인덱스 순서는 상관 없음. logit 함수는 열 이름 기반으로 매핑하기 때문에 

logit 은 로지스틱 회귀 모형을 만드는 것. 
: 가중치나 회귀계수 값들이 결정되지 않은 채, 껍데기 (변수들의 연결 관계 구속조건) 만 만들어진 상태 

model.fit() 
: 설계된 미지의 함수 시스템에 실제 데이터를 주입하여 오차를 최소화하는 최적의 고유파라미터를 찾아내고 명령 
내부적으로 뉴턴-랩슨 (Newton-Raphson) 같은 수치해석적 반복 최적화 알고리즘을 가동함. 
'''

# 오즈비 계산
odds_ratio_income = np.exp(result_income.params['income'])
'''
 오즈비 : 실대 대비 성공의 비율 
 로지스틱 회귀 분석은 확률을 구하고 (범위가 [0,1] 이라 직선으로 추정 불가) 오즈를 구한 다음 로즈 오그를 구한다. 
  그래서 오즈비도 exp 가 들어간다. 
    '''

Optimization terminated successfully.
         Current function value: 0.692599
         Iterations 3

In [ ]:
# 문제 1-2: 독립변수 income만 사용해 학습한 모델에서 test 데이터의 purchase를 예측하고, 정확도 계산
predictions_income = result_income.predict(test)
predicted_classes_income = (predictions_income > 0.5).astype(int)
'''
.predict() 의 결과 내부의 시그모이드함수를 거쳐 확률을 소숫점 데이터로 반환한다.
하지만 우리 알고 싶은 정답표는 어느 성공 / 실패이기 때무넹 임계값을 넘으면 성공으로 반환시킨다. 이 임계값이 0.5 
'''
# 정확도 계산 
accuracy_income = (predicted_classes_income == test['purchase']).mean()
'''
정확도는 맞춘갯수 / 전체 데이터 수이다. 그래서 평균 내줌. 
'''

In [ ]:
# 문제 1-3: 독립변수 income만 사용해 학습한 모델의 로짓 우도 계산
log_likelihood_income = result_income.llf
## .llf 는 학습이 완료된 결과 객체가 가지고 있는 '속성' 이다.

In [42]:
# 문제 1-4: 독립변수 income만 사용해 학습한 모델의 유의확률(p-value) 계산 
p_value_income = result_income.pvalues['income']

In [43]:
odds_ratio_income, accuracy_income, log_likelihood_income, p_value_income

(np.float64(1.0000019601805765),
 np.float64(0.5066666666666667),
 np.float64(-242.40981957168498),
 np.float64(0.5964910811075139))

In [44]:
# 정확도 사이킷런 활용
from sklearn.metrics import accuracy_score
accuracy_score(test['purchase'],predicted_classes_income)

0.5066666666666667

## T3-17 잔차이탈도
고객 정보를 나타낸 데이터이다. 주어진 데이터에서 500개 중 앞에서부터 300개는 train으로, 200개는 test 데이터로 나눈다. 모델을 학습(적합)할 때는 train 데이터를 사용하고, 예측할 때는 test 데이터를 사용한다. 모델은 로지스틱 회귀를 써서 고객이 특정 제품을 구매할지 여부를 예측하되, 페널티는 부과하지 않는다.  

Q. age, income, marital_status 변수를 독립변수로 purchase를 종속변수로 사용하여 로지스틱 회귀 모형을 만들고, 잔차이탈도를 구하시오. (반올림하여 소수 넷째자리까지 계산)

In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\Customer_Data.csv")
display(df.head(3))

train = df[:300]
test = df[300:]

   age  income  marital_status  children  gender  purchase
0   62  111980               1         2       1         0
1   65  107314               0         3       1         0
2   18   56209               1         1       1         1

In [46]:
from statsmodels.formula.api import logit 
model = logit('purchase ~ age+income+marital_status',data=train).fit()
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.687415
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:               purchase   No. Observations:                  300
Model:                          Logit   Df Residuals:                      296
Method:                           MLE   Df Model:                            3
Date:                Thu, 04 Jun 2026   Pseudo R-squ.:                0.007474
Time:                        14:57:42   Log-Likelihood:                -206.22
converged:                       True   LL-Null:                       -207.78
Covariance Type:            nonrobust   LLR p-value:                    0.3756
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.3407      0.452      0.753      0.451      -0.546       1.227
age               -0.0094      0.008     -1.236      0.216      -0.024       0.005
income          3.636e-06   4.02e-06      0.904      0.366   -4.25e-06    1.15e-05
marital_status    -0.2192      0.235     -0.931      0.352      -0.680       0.242
==================================================================================

In [47]:
print(round(-2*model.llf,2))

412.45

In [48]:
# summary 만 보고 계산하면 소수점이 모두 나오지 않기 때문에 차이가 있음
-2 * -206.22

412.44

In [49]:
# 방법 2 glm 활용
from statsmodels.formula.api import glm 
import statsmodels.api as sm
# glm 모델 적함
formula = "purchase ~ age + income + marital_status"
model = glm(formula, data=train, family=sm.families.Binomial()).fit()

# 잔차이탈도 계산
print(model.summary())
print(round(model.deviance,2))

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               purchase   No. Observations:                  300
Model:                            GLM   Df Residuals:                      296
Model Family:                Binomial   Df Model:                            3
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -206.22
Date:                Thu, 04 Jun 2026   Deviance:                       412.45
Time:                        15:09:21   Pearson chi2:                     300.
No. Iterations:                     4   Pseudo R-squ. (CS):            0.01030
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.3407      0.452      0.753      0.451      -0.546       1.227
age               -0.0094      0.008     -1.236      0.216      -0.024       0.005
income          3.636e-06   4.02e-06      0.904      0.366   -4.25e-06    1.15e-05
marital_status    -0.2192      0.235     -0.931      0.352      -0.680       0.242
==================================================================================
412.45

로지스틱 회귀에서 이탈도 (Deviataion)
 - 모델이 실제 데이터를 얼마나 설명하지 못하는지(오차의 크기) 를 나타내는 척도
 - Residual Deviance = -2 * Log-Likelihood 

Logit 메서드 메커니즘
1. 확률에서 Log-odds 공간으로
     - 확률 P 를 선형 연산이 가능한 Log-odds 공간으로 변환한다. 
2. 최대우도추정법(MLE) 과 뉴턴-랩슨 알고리즘으로 최적화
3. Sigmoid 함수를 통해 예측

## T3-18 AIC/BIC 계산  
독립변수(Pregnancies, BMI, DiabetesPedigreeFunction)를 사용하여 로지스틱 회귀 모델을 학습하고, 학습된 모델의 AIC와 BIC 값을 계산하세요.(종속변수는 Outcome)  

1. 모델의 로그 우도 (Log-Likelihood) 를 기반으로 AIC와 BIC 값을 계산하세요.

In [50]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\diabetes_train.csv")

display(df.head(3))

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,377,1,87,60,37,75,37.2,0.509,22,0
1,370,3,173,82,48,465,38.4,2.137,25,1
2,408,8,197,74,0,0,25.9,1.191,39,1

In [51]:
from statsmodels.formula.api import logit 

formula = "Outcome ~ Pregnancies + BMI + DiabetesPedigreeFunction"
model = logit(formula, data=df).fit()
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.549382
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  576
Model:                          Logit   Df Residuals:                      572
Method:                           MLE   Df Model:                            3
Date:                Thu, 04 Jun 2026   Pseudo R-squ.:                  0.1417
Time:                        15:19:34   Log-Likelihood:                -316.44
converged:                       True   LL-Null:                       -368.68
Covariance Type:            nonrobust   LLR p-value:                 1.703e-22
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                   -5.0805      0.567     -8.966      0.000      -6.191      -3.970
Pregnancies                  0.1754      0.029      6.012      0.000       0.118       0.233
BMI                          0.0984      0.015      6.402      0.000       0.068       0.128
DiabetesPedigreeFunction     0.9629      0.287      3.351      0.001       0.400       1.526
============================================================================================

In [52]:
print(model.aic)
print(model.bic)

640.8879324373285
658.312363080112

2. Pregnancies 를 범주형 변수로 처리하여 로지스틱 회귀 모델을 학습하세요. (독립변수 (Pregnancies, BMI, DiabetesPedigreeFunction) 를 사용)

In [54]:
from statsmodels.formula.api import logit 

formula = "Outcome ~ C(Pregnancies) + BMI + DiabetesPedigreeFunction"
model = logit(formula, data=df).fit()
print(model.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.528387
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  576
Model:                          Logit   Df Residuals:                      557
Method:                           MLE   Df Model:                           18
Date:                Thu, 04 Jun 2026   Pseudo R-squ.:                  0.1745
Time:                        15:21:31   Log-Likelihood:                -304.35
converged:                      False   LL-Null:                       -368.68
Covariance Type:            nonrobust   LLR p-value:                 9.591e-19
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                   -4.8968      0.650     -7.539      0.000      -6.170      -3.624
C(Pregnancies)[T.1]         -0.2059      0.371     -0.556      0.579      -0.932       0.521
C(Pregnancies)[T.2]         -0.3721      0.402     -0.925      0.355      -1.160       0.416
C(Pregnancies)[T.3]          0.7234      0.413      1.750      0.080      -0.087       1.534
C(Pregnancies)[T.4]          0.2712      0.429      0.632      0.528      -0.570       1.113
C(Pregnancies)[T.5]          0.3005      0.439      0.685      0.493      -0.560       1.161
C(Pregnancies)[T.6]          0.4865      0.445      1.093      0.274      -0.386       1.359
C(Pregnancies)[T.7]          1.6367      0.471      3.475      0.001       0.713       2.560
C(Pregnancies)[T.8]          1.9762      0.525      3.765      0.000       0.947       3.005
C(Pregnancies)[T.9]          1.6632      0.535      3.112      0.002       0.616       2.711
C(Pregnancies)[T.10]         1.3106      0.558      2.349      0.019       0.217       2.404
C(Pregnancies)[T.11]         1.8993      0.900      2.111      0.035       0.136       3.663
C(Pregnancies)[T.12]        -0.1290      1.162     -0.111      0.912      -2.406       2.148
C(Pregnancies)[T.13]         0.7003      0.790      0.887      0.375      -0.848       2.248
C(Pregnancies)[T.14]        22.9916   4.01e+04      0.001      1.000   -7.87e+04    7.87e+04
C(Pregnancies)[T.15]        32.4173   6.58e+06   4.93e-06      1.000   -1.29e+07    1.29e+07
C(Pregnancies)[T.17]        31.3997   6.61e+06   4.75e-06      1.000    -1.3e+07     1.3e+07
BMI                          0.1005      0.016      6.237      0.000       0.069       0.132
DiabetesPedigreeFunction     0.9695      0.298      3.250      0.001       0.385       1.554
============================================================================================

c:\Users\user\anaconda3\envs\ML\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [55]:
print(model.aic)
print(model.bic)

646.7016807700858
729.4677263233077

AIC, BIC : 여러 개의 예측 모델 중 어떤 모델이 가장 좋은 가성비를 가졌는지 평가하는 통계적 기준. 낮을 수록 좋음. 

$\text{AIC} = -2\ln(L)+2k$  
$\text{BIC} = -2\ln(L)+k\ln(n)$  

L : likelihood. 모델이 데이터를 잘 맡출수록 $-2\ln(L)$ 이 작아진다.   
k : 사용된 파라미터 갯수  
n : 데이터 샘플의 총 갯수   

AIC (Akaike Information Criterion) : 변수 개수 (k) 개가 늘어날 때마다 2k 만큼 고정된 벌점을 부여한다. 데이터의 크기와 관계 없이 벌점이 일정하여 데이너가 많아질수록 모델이 약간 복잡해지는 경향이 있다. 

BIC (Bayesian Information Criterion) : 변수 개수가 늘어날 때 부여하는 벌점이 $k\ln(n)$ 따라서 샘플 수가 많아질수록 변수 추가에 대한 패널티가 기하급수적으로 무거워진다. 따라서 변수가 적은 모델을 선택하려는 경향이 있다.

## T3-19 다중 선형회귀

1. 모든 변수를 사용하여 OLS 모델을 적합하고, 회귀계수 중 가장 큰 값은?
2. 유의미하지 않은 변수를 제거한 후 모델을 다시 적합하고, 회귀계수 중 가장 작은 변수명은?
3. 2번 모델의 R-squared 값을 계산하고 해석하세요.
4. 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y 값을 예측하세요.
5. 1번 모델에서 x1, x2, x3, x4의 상관관계를 계산하고 가장 큰 상관계수를 구하시오. (단, 자기 상관관계 제외)
6. x1과 x2만을 예측 변수로 사용하는 모델을 적합하고, 전체 모델과 R-squared 값을 구하시오.
7. 잔차(residual) 분석을 수행하고, 잔차의 표준편차를 구하시오.
8. 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y의 신뢰구간 하한(97% 신뢰수준)을 구하세요.
9. 1번 모델에서 새로운 데이터(x1=5, x2=12, x3=10, x4=3)에 대해 y의 예측구간 상한(97% 신뢰수준)을 구하세요.

In [56]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\Desktop\GitHub\BigData_Analysis_Exam\Data\t3_regression_data.csv")
display(df.head(3))

         x1         x2         x3        x4          y
0  1.354882  13.660146  12.025720  2.265464 -10.090372
1  8.878517  12.798070  14.194644  4.694667   7.798310
2  9.326056  18.815027   9.817460  2.519119  -2.287519

In [60]:
# 1. 모든 변수를 사용하여 OLS 모델을 적합하고, 회귀계수 중 가장 큰 값은? 
import statsmodels.formula.api as smf 

model_full = smf.ols('y ~ x1 + x2 + x3 + x4',data=df).fit()
print("1. 전체 모델 : ")
print(model_full.summary())

1. 전체 모델 :
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     1984.
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           1.39e-90
Time:                        15:35:21   Log-Likelihood:                -130.88
No. Observations:                 100   AIC:                             271.8
Df Residuals:                      95   BIC:                             284.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9816      0.740      4.029      0.000       1.512       4.451
x1             1.9979      0.030     66.384      0.000       1.938       2.058
x2            -1.4924      0.034    -44.274      0.000      -1.559      -1.425
x3             0.4633      0.033     13.837      0.000       0.397       0.530
x4             0.0203      0.078      0.260      0.796      -0.135       0.175
==============================================================================
Omnibus:                        2.161   Durbin-Watson:                   1.921
Prob(Omnibus):                  0.340   Jarque-Bera (JB):                1.718
Skew:                           0.313   Prob(JB):                        0.424
Kurtosis:                       3.140   Cond. No.                         155.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [61]:
# 유의미하지 않은 변수를 제거한 후 모델 재적합
# 유의미한 변수만 골라 새로운 모델 적합
model_refit = smf.ols('y ~ x1+x2+x3',data=df).fit()
print("2. 유의미한 변수로 재적합한 모델:")
print(model_refit.summary())

2. 유의미한 변수로 재적합한 모델:
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.988
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     2672.
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           2.55e-92
Time:                        15:36:25   Log-Likelihood:                -130.91
No. Observations:                 100   AIC:                             269.8
Df Residuals:                      96   BIC:                             280.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0628      0.667      4.589      0.000       1.738       4.388
x1             1.9986      0.030     67.020      0.000       1.939       2.058
x2            -1.4942      0.033    -45.529      0.000      -1.559      -1.429
x3             0.4636      0.033     13.923      0.000       0.398       0.530
==============================================================================
Omnibus:                        2.285   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.319   Jarque-Bera (JB):                1.836
Skew:                           0.324   Prob(JB):                        0.399
Kurtosis:                       3.140   Cond. No.                         138.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [62]:
# 3. 초기 모델의 R-squared 값 계산
print("3. 초기 모델의 R-squared 값 : ",model_refit.rsquared)

3. 초기 모델의 R-squared 값 :  0.9881643592045125

In [63]:
# 4. 새로운 데이터 (x1=5, x2=12, x3=10, x4=3) 에 대해 y 예측
new_data = pd.DataFrame({'x1': [5], 'x2': [12], 'x3': [10], 'x4': [3]})
y_pred = model_full.predict(new_data)
print("4. 새로운 데이터 포인트에 대한 예측값 : ",y_pred.iloc[0])

4. 새로운 데이터 포인트에 대한 예측값 :  -0.24330845820174374

In [64]:
# 5. 독립 변수 간의 상관관계 계산
correlation_matrix = df.corr()
print("5. 예측 변수 간의 상관관계 행렬 : ")
print(correlation_matrix)

5. 예측 변수 간의 상관관계 행렬 :
          x1        x2        x3        x4         y
x1  1.000000 -0.115152  0.080456  0.117670  0.822594
x2 -0.115152  1.000000 -0.164049 -0.224881 -0.627445
x3  0.080456 -0.164049  1.000000  0.075652  0.301941
x4  0.117670 -0.224881  0.075652  1.000000  0.218884
y   0.822594 -0.627445  0.301941  0.218884  1.000000

In [65]:
# 6. x1 과 x2 만을 사용한 모델 적합 및 R-squared 값 
model_x1_x2 = smf.ols('y ~ x1+x2',data=df).fit()
print("6. x1과 x2만 사용한 모델의 R-squared 값 : ",model_x1_x2.rsquared)

6. x1과 x2만 사용한 모델의 R-squared 값 :  0.9642665748957848

In [66]:
# 7. 잔차 분석 수행 
residuals = model_full.resid 
print("7. 잔차의 표준편차 : ")
print(residuals.std())

7. 잔차의 표준편차 :
0.9001841451852483

In [67]:
# 8. 1번 모델에서 새로운 데이터에 대해 y의 신뢰구간 하한 (97% 신뢰 수준) 을 구하세요 
pred_conf_int_97 = model_full.get_prediction(new_data).summary_frame(alpha=0.03)
conf_lower_97 = pred_conf_int_97['mean_ci_lower'].iloc[0]
print("10. y 의 신뢰구간 하한 (97% 신뢰수준) : ",conf_lower_97)

10. y 의 신뢰구간 하한 (97% 신뢰수준) :  -0.5402306644367606

In [68]:
# 9. 1 번 모델에서 새로운 데이터에 대해 y의 예측구간 상한을 구하세요
pred_upper_97 = pred_conf_int_97['obs_ci_upper'].iloc[0]
print("11. y의 예측구간 상한(97% 신뢰수준):", pred_upper_97)

11. y의 예측구간 상한(97% 신뢰수준): 1.802933556874058

## T3-20 비모수검정 (Wilcoxon)  
베스킨라빈스는 쿼트(Quart) 아이스크림의 중앙값이 620g이라고 주장하고 있습니다. 저는 실제로 이 아이스크림의 중앙값이 620g보다 무겁다고 주장합니다. 다음은 20개의 쿼트 아이스크림 샘플의 무게 측정 결과입니다. 이 측정 결과를 바탕으로 나의 주장이 사실인지 비모수 검정(Wilcoxon Signed-Rank Test)을 통해 검정해보십시오. p-value값을 반올림하여 소수점 둘째 자리까지 계산 

- 귀무가설: "베스킨라빈스 쿼트 아이스크림의 중앙값은 620g이다." 
- 대립가설: "베스킨라빈스 쿼트 아이스크림의 중앙값은 620g보다 무겁다."

In [69]:
import pandas as pd
data = {
    "weight": [630, 610, 625, 615, 622, 618, 623, 619, 620, 624, 616, 621, 617, 629, 626, 620, 618, 622, 625, 615, 
               628, 617, 624, 619, 621, 623, 620, 622, 618, 625, 616, 629, 620, 624, 617, 621, 623, 619, 625, 618,
               622, 620, 624, 617, 621, 623, 619, 625, 618, 622]
}
df = pd.DataFrame(data)

In [70]:
from scipy.stats import wilcoxon  

med=620 

print(wilcoxon(df['weight']-med,alternative='greater'))

WilcoxonResult(statistic=np.float64(684.0), pvalue=np.float64(0.029661945180945556))

In [71]:
result = wilcoxon(df["weight"]-med, alternative='greater')
p_value = round(result.pvalue,2)
print(p_value)

0.03

비모수검정 
- 모수가 정규분포가 아닌것을 검정하는 것 
- 데이터 샘플 갯수가 적거나, 왼오로 치우쳐져 있으면 사용 
- 일표본 t 검정, 독립표본 t-검정등은 모집단이 정규분포를 따른다는 가정 하에 작동 (모수적 방법)

1. 윌콕슨 부호순위 검정 (Wilcoxon Signed-Rank Test) 
- 매칭되는 t-검정 : 대응표본 t-검정
- 동일한 집단을 대상으로 두 데이터의 중앙값의 차이가 잇는지 검정한다.
- (후-전) 의 차이 구하기 => 부호 떼고 절댓값으로 순위 매기기 => 양과 음의 부호를 가진 순위들의 합을 비교하여 쏠려있는지 확인

2. 윌콕슨 순위합 검정 (Wilcoxon Rank-Sum Test)
- 매칭되는 t-검정 : 독립표본 t-검정 (Independent two-sample test)
- 서로 독립된 두 집단의 분포 중앙값이 서로 같은지 다른지 검정