# 작업형 제1유형

1. 각 제품보고서별 처리 시간 (처리시각과 신고시각의 차이) 칼럼(초단위) 을  생성 후 공장별 처리 시간의 평균을 산출하시오. 산출된 결과를 바탕으로 평균 처리시간이 3번째로 적은 공장명을 구하시오

In [2]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_1.csv")
display(df.head(3))

,제품보고서번호,공장명,결함유형,신고일자,신고시각,처리일자,처리시각,작업자직업명,사고발생장소
0,202200000001M25795,공장B,기계 결함,20220722,205914,20221027,184738,기술자,라인5
1,202200000002M10860,공장B,품질 문제,20220622,31050,20221109,132745,검사원,라인3
2,202200000003M86820,공장B,전기 결함,20220424,140320,20221130,35714,기술자,라인2

2. STATION_ADDR1 변수에서 구 정보만 추출한 후, 마포구, 성동구의 평균 이동거리를 구하시오

In [3]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_2.csv")
display(df.head(3))

,rent_date,rent_place,using_time,dist,bill_type,STATION_ADDR1,STATION_ID,STATION_LATITUDE,STATION_LONGITUDE
0,2019-03-19 00:42:26,ST-920,6,1660,BIL_002,서울특별시 구로구 경인로40길 47,ST-920,37.494995,126.858254
1,2019-02-14 10:53:40,ST-148,27,4530,BIL_004,서울특별시 중구 을지로 100,ST-148,37.565990,126.987793
2,2019-02-22 17:31:49,ST-10,28,4240,BIL_002,서울특별시 마포구 양화로 93,ST-10,37.552746,126.918617

3. 분기별 총 판매량 (제품 A~E의 합계) 의 월평균을 구하고, 월평균이 최대인 연도와 분기를 구하시오

In [4]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_3.csv")
display(df.head(3))

         기간  제품A  제품B  제품C  제품D  제품E
0  2018년_1월  890  567  274  762  691
1  2018년_2월  270  831  930  539  393
2  2018년_3월  233  580  687  601  944

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오 (분류 예측값 제출)
** 제출 형식은 ID, pred 두 칼럼만 존재해야한다. (평가지표 : macro f1-score)

In [7]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_test.csv")

display(train.head(3))

,level_0,ID,Marital Status,Application mode,Course,Daytime/evening attendance,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Educational special needs,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Target
0,0,3949,1_,43_,9147_,1_,1_,1_,1_,19_,9_,10_,0_,0_,0,5,9,5,Graduate
1,1,560,1_,53_,9003_,1_,42_,1_,3_,38_,141_,151_,0_,1_,7,12,18,11,Graduate
2,2,3186,1_,39_,9130_,1_,10_,1_,12_,36_,90_,90_,0_,1_,0,5,13,0,Dropout

# 작업형 제3유형

문제1 어느 학교에서 50명의 학생들을 대상으로 새로운 학습 프로그램의 효과를 조사하고자한다. 각 학생에 대해 학습 전과 학습 후의 시험 점수를 측정하였다.   


(1) 학습 전과 학습 후의 시험 점수의 평균과 표준편차를 구하시오 (소숫점 둘째 자리까지 반올림)  
(2) 학습 전후의 점수 차이가 유의미한지 검정하기 위해 대응표본 t-검정을 수행하고, 검정통계량을 계산하시오.  (소숫점 둘째 자리까지 반올림)  
(3) p-value를 바탕으로 유의수준 5%에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소숫점 셋째 자리까지 반올림)

In [8]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_1.csv")
display(df.head(3))

      before      after
0  87.640523  88.163191
1  74.001572  80.936085
2  79.787380  82.233354

문제2 어느 회사가 조사한 고객 데이터는 100개의 샘플로 이루어져 있으며, 각 샘플에는 고객의 나이, 소득, 가족 수, 그리고 제품 구매 여부가 포함되어 있다. 로지스틱 회귀 분석을 통해 고객의 제품 구매 여부를 예측하고자 한다. (임계값 0.5 기준)  

(1) 로지스틱 회귀 분석을 수행하고, 소득 변수의 오즈비를 계산하시오.  
(2) train 데이터 기준의 잔차 이탈도 (Residual Deviance) 를 계산하시오.  
(3) test 데이터로 오분류율을 계산하시오.

In [9]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_2_test.csv")
display(train.head(3))

   age        income  family_members  purchase
0   37  43620.800179               2         0
1   56  60865.620200               3         1
2   21  39500.939224               2         0