# 작업형 제1유형

1. 다음의 데이터는 대륙별 국가의 맥주소비량을 조사한 것이다.   

(1) 평균 맥주소비량이 가장 많은 대륙을 구하시오  
(2) 이전 문제에서 구한 대륙에서 5번째로 맥주소비량이 많은 나라를 구하시오  
(3) 이전 문제에서 구한 나라의 평균 맥주소비량을 구하시오 (소수첨 첫째 자리에서 반올림)

In [8]:
import numpy as np 
import pandas as pd

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_1_1.csv")
display(df.head(3))

   대륙           국가  맥주소비량
0  AS  Afghanistan    102
1  AS  Afghanistan    435
2  AS  Afghanistan    348

In [ ]:
df2 = df.groupby(['대륙'])['맥주소비량'].mean().reset_index()
display(df2)

# 1. 평균 맥주소비량이 가장 큰 행의 '정수 인덱스(방 번호)'를 찾습니다. (예: 3)
max_idx = df2['맥주소비량'].idxmax()

# 2. .loc[행_인덱스, '열_이름'] 구조로 대륙 이름을 쏙 빼옵니다.
print("평균 맥주소비량이 가장 많은 대륙 :")
print(df2.loc[max_idx, '대륙'])
# df.loc[행,열]

   대륙       맥주소비량
0  AF  248.314928
1  AS  249.705782
2  EU  248.684800
3  OC  249.379700
4  SA  253.357733

평균 맥주소비량이 가장 많은 대륙 :
SA

In [38]:
# SA 대륙에서 5번째로 맥주소비량이 많은 국가
df3 = df[(df['대륙']=='SA')]
df4 = df3.groupby(['국가'])['맥주소비량'].sum().reset_index()
df4 = df4.sort_values(['맥주소비량'],ascending=False).reset_index()
display(df4)
print("SA 대륙에서 5번째로 맥주소비량이 많은 국가 : ")
print(df4.loc[4,"국가"])

    index         국가   맥주소비량
0       7   Paraguay  165220
1       9   Suriname  163644
2       2     Brazil  162150
3       6     Guyana  160721
4      11  Venezuela  158136
5       1    Bolivia  157436
6       4   Colombia  157182
7       0  Argentina  157082
8       8       Peru  155438
9       3      Chile  154785
10     10    Uruguay  154416
11      5    Ecuador  153973

SA 대륙에서 5번째로 맥주소비량이 많은 국가 :
Venezuela

In [41]:
# Venezuela 의 평균 맥주 소비량 
df5 = df[(df['국가']=='Venezuela')]
print("Venezuela 의 평균 맥주 소비량 : ") 
ven_min = df5['맥주소비량'].mean()
print(round(ven_min,1))

Venezuela 의 평균 맥주 소비량 :
253.0

2. 다음의 데이터는 국가별로 방문객 유형을 조사한 것이다.  

(1) 관광객비율이 두 번째로 높은 나라의 '관광' 수를 구하시오    
관광객 비율 = 관광 / 합계 (소수점 넷째 자리에서 반올림)  
합계 = 관광 + 사무 + 공무 + 유학 + 기타   

(2) 관광 수가 두번째로 높은 나라의 '공무'수의 평균을 구하시오 (소수점 첫째 자리에서 반올림)   

(3) 이전에 구한 관광 수와 공무 수의 합계를 구하시오

In [42]:
import numpy as np 
import pandas as pd

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_1_2.csv")
display(df.head(3))

         국가    관광    사무   공무    유학   기타
0  남아프리카공화국  9198  1415  234   178  340
1       스페인  7127   409  422  3489  193
2      싱가포르  9640  1751  508  3536  709

In [43]:
df['합계'] = df['관광'] + df['사무'] + df['공무'] + df['유학'] + df['기타']
df['관광객 비율'] = round(df['관광'] / df['합계'],4)
df2 = df.sort_values(['관광객 비율'],ascending=False).reset_index()

display(df2)
print("관광객 비율이 두 번째로 높은 나라의 '관광' 수 : ")
print(df2.iloc[1]['관광'])

    index        국가    관광    사무   공무    유학   기타     합계  관광객 비율
0       4        일본  3980   160   64   204  303   4711  0.8448
1      11      이탈리아  7831   357  765   259  119   9331  0.8392
2      51       필리핀  7864   117  217  1328   78   9604  0.8188
3      24       모로코  9039    26  287  1673  115  11140  0.8114
4       0  남아프리카공화국  9198  1415  234   178  340  11365  0.8093
..    ...       ...   ...   ...  ...   ...  ...    ...     ...
95     91        중국   185   165  141   599  507   1597  0.1158
96     20   사우디아라비아   686  1905  905  2450  108   6054  0.1133
97     60       러시아   195   415  465  1204  464   2743  0.0711
98     93        독일   413  1612  926  4520  237   7708  0.0536
99     28        칠레   151   956  226  4722  950   7005  0.0216

[100 rows x 9 columns]

관광객 비율이 두 번째로 높은 나라의 '관광' 수 :
7831

In [ ]:
# 관광 수가 두번째로 높은 나라의 '공무' 수의 평균 
df3 = df[(df['국가']=='이탈리아')]
display(df3)
print("이탈리아 공무 수 평균 : ",round(df3['공무'].mean(),1))

      국가    관광    사무   공무    유학   기타     합계  관광객 비율
3   이탈리아  3358  1370  880  4620  459  10687  0.3142
11  이탈리아  7831   357  765   259  119   9331  0.8392
32  이탈리아  6911   724  297  1609  763  10304  0.6707

이탈리아 공무 수 평균 :  647.3

In [46]:
# 이전에 구한 관광 수와 공무 수의 합계 
print((df2.iloc[1]['관광'])+round(df3['공무'].mean(),1))

8478.3

3. CO(GT),NMHC(GT) 칼럼에 대해서 Min-Max 스케일러를 실행하고, 스케일링된 CO(GT), NMHC(GT) 칼럼의 표준편차를 구하시오. (소숫점 셋째 자리에서 반올림 )

In [61]:
import numpy as np 
import pandas as pd

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_1_3.csv")
display(df.head(3))

         Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)
0  13/10/2004  06.00.00  -200.0        798.0    -200.0       2.2
1  31/03/2005  10.00.00     1.3        996.0    -200.0       4.9
2  29/06/2004  07.00.00     3.4       1384.0    -200.0      23.5

In [62]:
from sklearn.preprocessing import MinMaxScaler 

scaler = MinMaxScaler()
df['CO(GT)'] = scaler.fit_transform(df[['CO(GT)']])
df['NMHC(GT)'] = scaler.fit_transform(df[['NMHC(GT)']])
display(df.head(3))

         Date      Time    CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)
0  13/10/2004  06.00.00  0.000000        798.0       0.0       2.2
1  31/03/2005  10.00.00  0.949976        996.0       0.0       4.9
2  29/06/2004  07.00.00  0.959887       1384.0       0.0      23.5

In [66]:
print("CO(GT) 칼럼의 표준 편차 : ")
print(round(df['CO(GT)'].std(),3))
print("NMHC(GT) 칼럼의 표준편차 : ")
print(round(df['NMHC(GT)'].std(),3))

CO(GT) 칼럼의 표준 편차 :
0.367
NMHC(GT) 칼럼의 표준편차 :
0.146

In [65]:
dat = df.loc[:,['CO(GT)','NMHC(GT)']]
scaled_data = scaler.fit_transform(dat)

co_std = scaled_data[:,0].std().round(2)
nmhc_std = scaled_data[:,1].std().round(2)
print(co_std, nmhc_std)

0.37 0.15

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오 (Target : count)   
제출 형식은 ID, pred 두 칼럼만 존재해야 한다. (평가지표 : MAE)

In [57]:
import numpy as np 
import pandas as pd

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_2_test.csv")
display(train.head(3))
display(test.head(3))

,ID,holiday,workingday,weather,temp,atemp,humidity,windspeed,count
0,1017,No,No,Light Rain,11.48,12.120,100,27.9993,11
1,8921,No,Yes,Clear,27.88,31.820,79,16.9979,27
2,878,No,Yes,Clear,12.30,13.635,70,31.0009,7

      ID holiday workingday weather   temp  atemp  humidity  windspeed  count
0   4775      No         No   Clear   9.84  12.12        60     8.9981    NaN
1  10539      No        Yes   Clear  18.04  21.97        41    19.0012    NaN
2   8229     Yes         No   Clear  27.06  31.06        69     0.0000    NaN

In [67]:
# EDA 

print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          378 non-null    int64
 1   holiday     378 non-null    object
 2   workingday  378 non-null    object
 3   weather     378 non-null    object
 4   temp        378 non-null    float64
 5   atemp       378 non-null    float64
 6   humidity    378 non-null    int64
 7   windspeed   378 non-null    float64
 8   count       378 non-null    int64
dtypes: float64(3), int64(3), object(3)
memory usage: 26.7+ KB
None

In [68]:
# 최종 결과 제출을 위해서 ID 칼럼을 따로 저장합니다. 
test_id = test['ID']

In [71]:
# 모델 성능 확인을 위해 훈련 데이터의 일부를 검증 데이터로 나눈다.
train_X = train.drop(['count'],axis=1)
train_y = train['count']

test_X = test.drop(['count'],axis=1)
test_y = test['count']

from sklearn.model_selection import train_test_split
train_X, valid_X, train_y, valid_y= train_test_split(train_X, train_y, random_state=42, test_size=0.3)
print(train_X.shape, valid_X.shape, train_y.shape, valid_y.shape)
display(train_X.head(3))
display(valid_X.head(3))

(264, 8) (114, 8) (264,) (114,)

        ID holiday workingday weather   temp   atemp  humidity  windspeed
373  10306      No        Yes   Clear  12.30  15.150        52    11.0014
278   1871      No        Yes   Clear  16.40  20.455        62    22.0028
249  10381      No         No    Mist  13.12  16.665        57     7.0015

       ID holiday workingday weather   temp   atemp  humidity  windspeed
287  4050      No        Yes    Mist  22.96  26.515        68     8.9981
329  7151     Yes         No   Clear  21.32  25.000        83     8.9981
323  1822      No        Yes    Mist  25.42  30.305        69     8.9981

In [74]:
# 범주형 변수에 원핫 인코딩 수행
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

cat_columns = train_X.select_dtypes('object').columns.to_list()
print("cat columns : ",cat_columns)
train_X_pre = onehotencoder.fit_transform(train_X[cat_columns])
valid_X_pre = onehotencoder.fit_transform(valid_X[cat_columns])
test_X_pre = onehotencoder.fit_transform(test_X[cat_columns])

cat columns :  ['holiday', 'workingday', 'weather']

In [76]:
# RandomForest
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=42)
rf.fit(train_X_pre,train_y)

RandomForestRegressor(random_state=42)

In [77]:
# 검증 데이터를 활용하여 모형 성능 확인
from sklearn.metrics import mean_absolute_error 

pred_val = rf.predict(valid_X_pre)
print("valid MAE : ",mean_absolute_error(valid_y,pred_val))

valid MAE :  155.38795026085148

In [79]:
# 테스트 데이터를 활용하여 최종 예측 
test_pred = rf.predict(test_X_pre)
test_pred = pd.DataFrame(test_pred, columns = ['pred'])

In [80]:
# ID, pred 칼럼만 존재하는 결과 파일 생성
result = pd.concat([test_id, test_pred],axis=1)
print(result)
# result.to_csv('이름',index=False)

        ID        pred
0     4775  207.519684
1    10539  218.702436
2     8229  118.126345
3     8677  231.955814
4     5071  218.702436
..     ...         ...
161   2573  218.702436
162   3329  218.702436
163   2373  218.702436
164    959  218.702436
165   8589  231.955814

[166 rows x 2 columns]

# 작업형 제3유형

1. 어느 회사에서 직원들의 업무 효율성을 높이기 위한 새로운 소프트웨어를 도입하였다. 도입 전과 도입 후의 업무 처리 시간을 각각 측정하여 새로운 소프트웨어의 효과를 검증하고자 한다.

(1) 도입 전과 도입후의 업무처리 시간의 평균과 표준편차를 구하시오. (소숫점 둘째 자리까지 반올림)  
(2) 도입 전후의 업무처리 시간 차이가 유의미한지 부호 순위 검정을 실시하고, 검정통계량을 계산하시오. (소숫점 둘째 자리까지 반올림)  
(3) p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소숫점 셋째 자리까지 반올림)

In [81]:
import numpy as np 
import pandas as pd

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_3_1.csv")
display(df.head(3))

      before      after
0  10.646079  10.541545
1   8.600236   7.213333
2   9.468107   8.978912

In [82]:
# 도입 전과 후의 평균과 표준편차
print("도입 전의 평균 : {:.2f}, 표준편차 : {:.2f}".format(df['before'].mean(),df['before'].std()))
print("도입 후의 평균 : {:.2f}, 표준편차 : {:.2f}".format(df['after'].mean(),df['after'].std()))

도입 전의 평균 : 8.21, 표준편차 : 1.71
도입 후의 평균 : 7.23, 표준편차 : 1.96

In [87]:
# 도입 전후 시간 차이 부호 순위 검정
from scipy.stats import wilcoxon

statistic, p_value = wilcoxon(df['before'],df['after'])
print("검정통계량 : {:.2f}".format(statistic))

72.0
검정통계량 : 72.00

In [89]:
# p-value 바탕으로 귀무가설 기각/채택 여부
if p_value<0.05 : 
    print("귀무가설 기각")
else : 
    print("귀무가설 채택")

귀무가설 기각

2. 어느 회사에서 직원들의 생산성에 영향을 미치는 요인이 무엇인지 확인하고자 한다. 100명의 직원들을 대상으로 생산성 점수, 근무 시간, 연령, 그리고 경력을 조사하였다.  

(1) 훈련 데이터를 기준으로 생산성 점수 (productivity) 를 종속변수로 하고 근무 시간, 연령, 그리고 경력을 독립변수로 하는 다중회귀 분석을 수행한 후, 회귀계수가 가장 높은 변수를 구하시오. (다중회쉬모형 적합 시 절편 포함)  
(2) 유의수준 5% 하에서 각 독립변수가 생산성에 미치는 영향이 통계적으로 유의미한지 판단하고, 유의미한 변수 개수를 구하시오 (p-value 는 소숫점 넷째자리까지 반올림)  
(3) 테스트 데이터로 모델의 성능을 평가하시오 (R^2 산출)

In [91]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_3_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/8_3_2_test.csv")
display(train.head(3))
display(test.head(3))

   productivity      hours  age  experience
0    201.358765  49.753877   34          24
1    172.434251  35.934269   52           8
2    207.275322  51.204466   56          28

   productivity      hours  age  experience
0    160.320183  40.228793   35           8
1    169.602253  45.893898   44           4
2    171.564796  44.893690   46           9

In [92]:
import statsmodels.api as sm

# 독립 변수와 종속 변수 설정 (train 데이터 사용) 
X_train = train[['hours','age','experience']]
y_train = train['productivity']

X_train = sm.add_constant(X_train) # 상수항 추가 
model = sm.OLS(y_train, X_train).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           productivity   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     69.03
Date:                Wed, 10 Jun 2026   Prob (F-statistic):           1.20e-21
Time:                        23:17:31   Log-Likelihood:                -297.10
No. Observations:                  80   AIC:                             602.2
Df Residuals:                      76   BIC:                             611.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         67.2310     11.097      6.059      0.000      45.130      89.332
hours          1.6182      0.226      7.169      0.000       1.169       2.068
age            0.4311      0.110      3.904      0.000       0.211       0.651
experience     1.5323      0.124     12.380      0.000       1.286       1.779
==============================================================================
Omnibus:                        3.122   Durbin-Watson:                   1.692
Prob(Omnibus):                  0.210   Jarque-Bera (JB):                2.381
Skew:                           0.380   Prob(JB):                        0.304
Kurtosis:                       3.372   Cond. No.                         611.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [93]:
# 회귀계수가 가장 큰 변수를 출력 
coefficients = model.params[1:]
print("회귀계수가 가장 큰 변수 : ",coefficients.idxmax())

회귀계수가 가장 큰 변수 :  hours

In [94]:
# 유의수준 5% 하에서 p-value 를 확인하고, 유의미한 변수의 개수를 계산
p_values = model.pvalues[1:].round(4)
significant_vars = p_values[p_values<0.05]
num_significant_vars = len(significant_vars)

print("유의미한 변수 개수 : ",num_significant_vars)
print(significant_vars)

유의미한 변수 개수 :  3
hours         0.0000
age           0.0002
experience    0.0000
dtype: float64

In [98]:
# R^2 
# 독립 변수와 종속 변수 설정 (test 데이터 사용)
from sklearn.metrics import r2_score
X_test = test[['hours','age','experience']]
y_test = test['productivity']

X_test = sm.add_constant(X_test) # 상수항 추가
y_pred = model.predict(X_test) # 에측 수행
r2 = r2_score(y_test, y_pred) # R^2 계산
print("테스트 데이터 Rsquared : ",round(r2,3))

테스트 데이터 Rsquared :  0.804