# 작업형 제1유형

다음 데이터에서 ProductA 가격과 ProductB 가격이 모두 0원이 아닌 데이터를 필터링하고, ProductA와 ProductB의 가격 차이를 정의하시오. 각 도시별 가격 차이의 평균 중 가장 큰 값을 구하시오. (소수점 첫째 자리까지 반올림)

In [7]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_1_1.csv")
display(df.head(3))

  도시명  ProductA가격  ProductB가격
0  울산       25000       10000
1  인천       30000           0
2  광주       15000        8000

In [8]:
# EDA
print(df.isnull().sum())

도시명           0
ProductA가격    0
ProductB가격    0
dtype: int64

In [12]:
df2 = df[(df['ProductA가격']!=0)&(df['ProductB가격']!=0)]
df2['Diff'] = df2['ProductA가격']-df2['ProductB가격']
#df2 = df2.sort_values(['Diff'],ascending=False)
#display(df2.head(5))

df3 = df2.groupby(['도시명'])['Diff'].mean().reset_index()
df3 = df3.sort_values('Diff',ascending=False)
display(df3.head(3))
print(f"각 도시별 가격 차이의 평균중 가장 큰 값은 {round(df3.iloc[0]['Diff'],1)} 입니다.")

/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_79908/2886893301.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Diff'] = df2['ProductA가격']-df2['ProductB가격']

  도시명          Diff
4  서울  16250.000000
2  대전  15666.666667
3  부산  12500.000000

각 도시별 가격 차이의 평균중 가장 큰 값은 16250.0 입니다.

100 명의 키와 몸무게를 조사하여 적정 체중인지 판단할 수 있는 BMI 를 산출하려 한다. 아래 표를 참고하여 BMI를 기준으로 저체중, 정상, 과체중, 비만을 구분하고, 저체중인 사람과 비만인 사람의 총 합을 구하시오.
- 저체중 : BMI 18.5 미만
- 정상 : 18.5 이상 23 미만
- 과체중 : 23 이상 25 미만
- 비만 : 25 이상

$BMI = \frac{\text{몸무(kg)}}{\text{키}(m^2)}$ 
* 소숫점 첫째 자리까지 반올림

In [20]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_1_2.csv")
display(df.head(2))

   Height_cm  Weight_kg
0  165.02132  66.131592
1  183.21947  82.164648

In [23]:
df['BMI'] = round(df['Weight_kg']/((df['Height_cm']*1E-2)**2),1)

def classification(BMI):
    if BMI < 18.5 :
        return "저체중"
    elif 18.5 <= BMI < 23 :
        return "정상"
    elif 23<= BMI < 25 :
        return "과체중"
    else :
        return "비만"

df['비만도결과'] = df['BMI'].apply(classification)

df2 = df[(df['비만도결과']=='저체중') | (df['비만도결과']=='비만')]
print(f"저체중인 사람과 비만인 사람의 총 합은 {len(df2)} 명 입니다.")

저체중인 사람과 비만인 사람의 총 합은 74 명 입니다.

다음 데이터에서 연도별로 가장 큰 순생산량 (생산된 제품 수 - 판매된 제품 수) 을 가진 공장을 찾고, 순생산량의 합을 계산하시오.

In [31]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_1_3.csv")
display(df.head(2))

,factory,products_made_domestic,products_made_international,products_sold_domestic,products_sold_international,materials_received_domestic,materials_received_international,materials_used_domestic,materials_used_international,year
0,Factory B,1428,814,1633,274,550,362,1048,580,2020
1,Factory C,1752,369,868,699,692,250,340,563,2023

In [32]:
df['생산된 제품 수'] = df['products_made_domestic'] + df['products_made_international'] 
df['판매된 제품 수'] = df['products_sold_domestic'] + df['products_sold_international']
df['순생산량'] = df['생산된 제품 수'] - df['판매된 제품 수']

In [33]:
display(df.head(3))

,factory,products_made_domestic,products_made_international,products_sold_domestic,products_sold_international,materials_received_domestic,materials_received_international,materials_used_domestic,materials_used_international,year,생산된 제품 수,판매된 제품 수,순생산량
0,Factory B,1428,814,1633,274,550,362,1048,580,2020,2242,1907,335
1,Factory C,1752,369,868,699,692,250,340,563,2023,2121,1567,554
2,Factory E,1263,657,800,835,1066,442,540,527,2021,1920,1635,285

In [39]:
max_production = df.loc[df.groupby(['year'])['순생산량'].idxmax()]

total_max_production_sum = max_production['순생산량'].sum()
display(max_production)
print("각 연도별 가장 큰 순생산량을 가진 공장의 순 생산량 : ")
print(max_production[['year','factory','순생산량']])
print(f"전체 기간의 해당 순생산량들의 합 : {total_max_production_sum}")

,factory,products_made_domestic,products_made_international,products_sold_domestic,products_sold_international,materials_received_domestic,materials_received_international,materials_used_domestic,materials_used_international,year,생산된 제품 수,판매된 제품 수,순생산량
12,Factory E,1962,957,553,332,1250,238,351,402,2020,2919,885,2034
75,Factory A,1778,590,765,355,1185,523,620,433,2021,2368,1120,1248
96,Factory E,1797,948,400,871,438,355,743,170,2022,2745,1271,1474
49,Factory B,1917,581,739,727,709,295,1375,636,2023,2498,1466,1032

각 연도별 가장 큰 순생산량을 가진 공장의 순 생산량 :
    year    factory  순생산량
12  2020  Factory E  2034
75  2021  Factory A  1248
96  2022  Factory E  1474
49  2023  Factory B  1032
전체 기간의 해당 순생산량들의 합 : 5788

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오. (Target : DBP)  
* 제출 형식은 ID, pred 두 칼럼만 존재해야한다 (평가지표 : RMSE)

In [40]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_test.csv")
display(train.head(2))
display(test.head(2))

   level_0    ID  Age Gender   BMI  DBP   FPG  Chol   Tri   HDL   LDL   ALT
0        0  2569   56    NaN  22.4   93  5.51  4.39  1.14  1.29  3.12  15.3
1        1  2215   33    NaN  22.1   75  5.51  3.32  0.75  1.15  1.95   9.7

,level_0,ID,Age,Gender,BMI,DBP,FPG,Chol,Tri,HDL,LDL,ALT
0,0,2856,39,NaN,22.2,83,5.3,3.63,0.79,1.400000,1.740000,13.0
1,1,3116,60,NaN,25.2,79,5.9,4.28,0.65,4.860753,4.860753,19.0

In [42]:
# EDA 
print("train 데이터의 null 결과")
print(train.isnull().sum())
print("test 데이터의 null 결과")
print(test.isnull().sum())

train 데이터의 null 결과
level_0     0
ID          0
Age         0
Gender     11
BMI         0
DBP         0
FPG         0
Chol        0
Tri         0
HDL         0
LDL         0
ALT         0
dtype: int64
test 데이터의 null 결과
level_0    0
ID         0
Age        0
Gender     7
BMI        0
DBP        0
FPG        0
Chol       0
Tri        0
HDL        0
LDL        0
ALT        0
dtype: int64

In [48]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   level_0  301 non-null    int64
 1   ID       301 non-null    int64
 2   Age      301 non-null    int64
 3   Gender   290 non-null    object
 4   BMI      301 non-null    float64
 5   DBP      301 non-null    int64
 6   FPG      301 non-null    float64
 7   Chol     301 non-null    float64
 8   Tri      301 non-null    float64
 9   HDL      301 non-null    float64
 10  LDL      301 non-null    float64
 11  ALT      301 non-null    float64
dtypes: float64(7), int64(4), object(1)
memory usage: 28.3+ KB
None

In [59]:
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_test.csv")
train = train.dropna(subset=['Gender'])
test = test.dropna(subset=['Gender'])
display(train.head(3))

train_X = train.drop(['DBP'],axis=1)
train_y = train['DBP']
test_X = test.drop(['DBP'],axis=1)
test_y = test['DBP']
#print(train_X['Gender'].unique())
def gender_onehot(gender) : 
    if gender == "M" : 
        return 0 
    else : 
        return 1
train_X['Gender'] = train_X['Gender'].apply(gender_onehot)
test_X['Gender'] = test_X['Gender'].apply(gender_onehot)
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
rf.fit(train_X,train_y)
y_pred = rf.predict(test_X)
from sklearn.metrics import root_mean_squared_error

RMSE = root_mean_squared_error(y_pred,test_y)
print(f"훈련 데이터로 학습한 모델을 테스트 데이터에 적용했을 때 RMSE 는 {round(RMSE,1)} 입니다.")

ID_columns = test_X['ID']
preds = y_pred
result = pd.DataFrame({'ID' : ID_columns, 'pred' : preds})
display(result)

    level_0    ID  Age Gender   BMI  DBP   FPG  Chol   Tri   HDL   LDL   ALT
11       11  2306   40      M  32.2   83  5.54  3.70  0.66  1.30  2.26  12.2
12       12  1752   34      F  22.6   77  4.80  4.18  1.28  1.41  2.18  28.9
13       13  1801   28      F  22.6   67  4.48  4.30  0.80  1.34  2.77  16.0

훈련 데이터로 학습한 모델을 테스트 데이터에 적용했을 때 RMSE 는 10.4 입니다.

       ID   pred
7    4140  83.25
8    3748  81.00
9    1364  75.40
10   3719  89.25
11   2692  76.04
..    ...    ...
124  3841  80.00
125  3003  73.20
126    94  72.77
127  2474  73.84
128  2053  80.66

[122 rows x 2 columns]

In [64]:
# 정답 코드 
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_2_test.csv")

test_id = test['ID']
train = train.drop(['level_0','ID'],axis=1)
test = test.drop(['level_0','ID'],axis=1)

# 데이터 분할
train_X = train.drop(['DBP'],axis=1)
train_y = train['DBP']
test_X = test.drop(['DBP'],axis=1)
test_y = test['DBP']

from sklearn.model_selection import train_test_split
train_X, valid_X, train_y, valid_y = train_test_split(train_X,train_y,test_size=0.3,random_state=42)

# Preprocessing
cat_cols = train_X.select_dtypes('object').columns.to_list()
num_cols = train_X.select_dtypes('number').columns.to_list()

# One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

onehotencoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
imputer = SimpleImputer(strategy = 'most_frequent')

train_X_categorical_imputed = imputer.fit_transform(train_X[cat_cols])
valid_X_categorical_imputed = imputer.transform(valid_X[cat_cols])
test_X_categorical_imputed = imputer.transform(test_X[cat_cols])

train_X_categorical_encoded = onehotencoder.fit_transform(train_X_categorical_imputed)
valid_X_categorical_encoded = onehotencoder.transform(valid_X_categorical_imputed)
test_X_categorial_encoded = onehotencoder.transform(test_X_categorical_imputed)

import numpy as np 
train_X_preprocessed = np.concatenate([train_X[num_cols], train_X_categorical_encoded],axis=1)
valid_X_preprocessed = np.concatenate([valid_X[num_cols], valid_X_categorical_encoded],axis=1)
test_X_preprocessed = np.concatenate([test_X[num_cols], test_X_categorial_encoded],axis=1)

# 모델 적합
from sklearn.ensemble import RandomForestRegressor 
rf = RandomForestRegressor(random_state=42)
rf.fit(train_X_preprocessed, train_y)
pred_val = rf.predict(valid_X_preprocessed)
# 모형 성능 확인
from sklearn.metrics import mean_squared_error 
mse = mean_squared_error(valid_y, pred_val)
rmse = np.sqrt(mse)
print("valid RMSE : ",rmse)

# 테스트 데이터로 예측
test_pred = rf.predict(test_X_preprocessed)
test_pred = pd.DataFrame(test_pred, columns=['pred'])

result  = pd.concat([test_id,test_pred],axis=1)
print(result.head(2))

valid RMSE :  11.643350222148452
     ID   pred
0  2856  75.09
1  3116  83.26

# 작업형 제3유형

어느 회사에서 100명의 직원을 대상으로 하루 업무 수행 시간을 조사하였다. K-S 검정을 통해 업무수행 시간이 정규분포를 따르는지 검정하고자 한다.  

1. 직원들의 업무 수행 시간의 평균과 표준편차르 구하시오 (소수점 셋째 자리까지 반올림)  
2. 직원들의 업무 수행 시간이 정규분포를 따르는지 K-S 검정을 실시하고, 검정통계량을 계산하시오 (소수점 셋째 자리까지 반올림)  
3. p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/ 채택 여부를 결정하시오. (p-value 는 소수점 셋째 자리까지 반올림)

In [60]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_3_1.csv")
display(df.head(3))

   work_hours
0   10.646079
1    8.600236
2    9.468107

In [68]:
print(f"직원들의 업무수행시간의 평균은 {round(df['work_hours'].mean(),3)} 이고 표준편차는 {round(df['work_hours'].std(),3)} 입니다.")

직원들의 업무수행시간의 평균은 8.09 이고 표준편차는 1.519 입니다.

In [69]:
from scipy.stats import kstest, norm 


statistic, pvalue = kstest(df['work_hours'],'norm',args = (df['work_hours'].mean(),df['work_hours'].std()))

print(f"K-S test 검정 통계량 : {round(statistic,3)}")

K-S test 검정 통계량 : 0.064

In [70]:
alpha =0.05

if pvalue < 0.05 : 
    print("귀무가설을 기각합니다.")
else : 
    print("귀무가설을 채택합니다.")

귀무가설을 채택합니다.

다음의 데이터는 주택들의 가격(price), 면적(area), 방의 개수(rooms), 연식(age)을 조사하여 기록한 것이다.  
1. 주택 가격을 종속변수로 하고, 면적, 방의 개수, 연식을 독립변수로 하는 다중회귀 분석을 수행하여, 회귀계수가 가장 높은 변수를 구하시오. (다중회귀모형 적합 시 절편 포함)  
2. 유의수준 5% 하에서 각 독립변수가 주택 가격에 미치는 영향이 통계적으로 유의미한 지 판단하고, 유의미한 변수 개수를 구하시오.

In [71]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_3_2.csv")
display(df.head(3))

           price        area  rooms  age
0  111842.374472  202.921570      2   11
1  109705.917098  162.004716      2    2
2  144253.316822  179.362140      5    5

In [72]:
import statsmodels.api as sm 
# 독립 변수와 종속 변수 설정
X = df[['area','rooms','age']]
y = df['price']

# 상수항 추가
X = sm.add_constant(X)

# 다중회귀 분석 모델 적합
model = sm.OLS(y, X).fit()

# 회귀계수 추출
coefficients = model.params[1:]
print("회귀계수가 가장 큰 변수 : ",coefficients.idxmax())

p_values = model.pvalues
import numpy as np 
print("유의미한 변수 개수 : ",np.sum(p_values<0.05))

회귀계수가 가장 큰 변수 :  rooms
유의미한 변수 개수 :  4

In [73]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/6_3_2.csv")
import statsmodels.formula.api as smf

formula = 'price ~ area + rooms + age'
model = smf.ols(formula=formula,data=df).fit()
coefficients = model.params[1:]
print("회귀계수가 가장 큰 변수 : ",coefficients.idxmax())

pvalue = model.pvalues
import numpy as np 
print("유의미한 변수 개수 : ",np.sum(pvalue<0.05))

회귀계수가 가장 큰 변수 :  rooms
유의미한 변수 개수 :  4