# 작업형 제1유형

다음 데이터에서 conventional 칼럼의 특수문자를 제거하고, IQR (3분위수 - 1분위수)를 구하시오. (소수점 첫째 자리에서 반올림)

In [1]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_1_1.csv")
display(df.head(3))

,minority,crime,poverty,language,highschool,housing,city,conventional,undercount,date
0,26.1,49,18.9,0.2,43.5,7.6,state,*,-0.04,2023-01-01
1,5.7,62,10.7,1.7,17.5,23.6,state,&,3.35,2023-01-02
2,18.9,81,13.2,3.2,27.6,8.1,state,*,2.48,2023-01-03

위 데이터에서 흑인 또는 히스패닉 비율 (minority) / 빈곤율 (poverty) > 2 이며, 도시 유형 (city) 이 state 인 도시의 범죄율 (crime) 평균을 구하시오. (소수점 첫째자리에서 반올림)

다음 데이터에서 2016년 9월 이후, 온도 (actual)의 평균을 구하시오. (소수점 첫째 자리에서 반올림)

In [2]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_1_2.csv")
display(df.head(3))

   year  month  day week  temp_2  temp_1  average  actual  friend
0  2016      1    1  Fri      45      45     45.6      45      29
1  2016      1    2  Sat      44      45     45.7      44      61
2  2016      1    3  Sun      45      44     45.8      41      56

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오 (Target : 1일 확률)  

제출형식은 ID, prob 두 칼럼만 존재해야 한다. (평가지표  : AUC)

In [3]:
import pandas as pd 
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_test.csv")

# 작업형 제3유형

어느 학교에서 학생들의 공부 시간과 시험 점수 간의 상관관계를 조사하고자 한다. 50명의 학생을 대상으로 하루 평균 공부 시간과 최근 시험 점수를 조사하였다.  

1. 학생들의 공부 시간과 시험 점수의 평균, 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)  
2. 공부 시간과 시험 점수 간의 상관관계를 조사하기 위한 피어슨 상관계수를 계산하시오. (소수점 셋째 자리까지 반올림)  
3. p-value를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소수점 셋째 자리까지 반올림)

In [4]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_3_1.csv")
display(df.head(3))

   study_hours  exam_scores
0     8.528105    66.045334
1     5.800314    78.869025
2     6.957476    69.891949

어느 마케팅 회사에서 세 가지 마케팅 캠페인 (A, B, C) 의 효과가 유의미하게 다른지를 조사하고자 한다. 각 캠페인에 대해 각각 50명의 고객을 랜덤으로 추출하여 만족도를 조사하였다.  

1. 각 캠페인의 만족도 점수의 평균, 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)  
2. 세 캠페인의 평균 만족도 점수가 유의미하게 다른지 검정하기 위해 ANOVA 검정을 수행하고, 검정 통계량을 계산하시오. (소수점 셋째 자리까지 반올림)  
3. p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value는 소수점 셋째 자리까지 반올림)

In [5]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_3_2.csv")
display(df.head(3))

  campaign  satisfaction_score
0        A           87.640523
1        A           74.001572
2        A           79.787380