# 작업형 제1유형

다음 데이터에서 conventional 칼럼의 특수문자를 제거하고, IQR (3분위수 - 1분위수)를 구하시오. (소수점 첫째 자리에서 반올림)

In [26]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_1_1.csv")
display(df.head(3))

,minority,crime,poverty,language,highschool,housing,city,conventional,undercount,date
0,26.1,49,18.9,0.2,43.5,7.6,state,*,-0.04,2023-01-01
1,5.7,62,10.7,1.7,17.5,23.6,state,&,3.35,2023-01-02
2,18.9,81,13.2,3.2,27.6,8.1,state,*,2.48,2023-01-03

In [27]:
df['conventional'] = df['conventional'].str.replace(r'[^a-zA-Z0-9가-힣\s]',"",regex=True)
print(df['conventional'].unique())

<StringArray>
[   '',   '4',  '19',   '0',  '29',  '56',  '14',  '40',   '8',  '11',  '75',
  '33',  '10',  '58',  '70',  '13',  '84',   '1',   '9', '100']
Length: 20, dtype: str

In [28]:
from sklearn.impute import SimpleImputer

df['conventional'] = df['conventional'].replace('',None)
imputer = SimpleImputer(strategy = 'most_frequent')
df[['conventional']] = imputer.fit_transform(df[['conventional']])
display(df.head(5))
print(df.info())

,minority,crime,poverty,language,highschool,housing,city,conventional,undercount,date
0,26.1,49,18.9,0.2,43.5,7.6,state,0,-0.04,2023-01-01
1,5.7,62,10.7,1.7,17.5,23.6,state,0,3.35,2023-01-02
2,18.9,81,13.2,3.2,27.6,8.1,state,0,2.48,2023-01-03
3,16.9,38,19.0,0.2,44.5,7.0,state,0,-0.74,2023-01-04
4,24.3,73,10.4,5.0,26.0,11.8,state,4,3.60,2023-01-05

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   minority      66 non-null     float64
 1   crime         66 non-null     int64
 2   poverty       66 non-null     float64
 3   language      66 non-null     float64
 4   highschool    66 non-null     float64
 5   housing       66 non-null     float64
 6   city          66 non-null     str
 7   conventional  66 non-null     str
 8   undercount    66 non-null     float64
 9   date          66 non-null     str
dtypes: float64(6), int64(1), str(3)
memory usage: 5.3 KB
None

In [29]:
df['conventional'] = pd.to_numeric(df['conventional'],errors='coerce')
Q1 = df['conventional'].quantile(0.25)
Q3 = df['conventional'].quantile(0.75)
print(f"IQR : {round(Q3-Q1,1)}")

IQR : 7.0

위 데이터에서 흑인 또는 히스패닉 비율 (minority) / 빈곤율 (poverty) > 2 이며, 도시 유형 (city) 이 state 인 도시의 범죄율 (crime) 평균을 구하시오. (소수점 첫째자리에서 반올림)

In [30]:
display(df.head(3))
df['minority ratio'] = round(df['minority']/df['poverty'],1)
df2 = df[(df['minority ratio']>2) & (df['city']=='state')]
display(f"소수 인종 및 도시유형 평균 : {round(df['crime'].mean(),1)}")

,minority,crime,poverty,language,highschool,housing,city,conventional,undercount,date
0,26.1,49,18.9,0.2,43.5,7.6,state,0,-0.04,2023-01-01
1,5.7,62,10.7,1.7,17.5,23.6,state,0,3.35,2023-01-02
2,18.9,81,13.2,3.2,27.6,8.1,state,0,2.48,2023-01-03

'소수 인종 및 도시유형 평균 : 63.1'

다음 데이터에서 2016년 9월 이후, 온도 (actual)의 평균을 구하시오. (소수점 첫째 자리에서 반올림)

In [31]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_1_2.csv")
display(df.head(3))

   year  month  day week  temp_2  temp_1  average  actual  friend
0  2016      1    1  Fri      45      45     45.6      45      29
1  2016      1    2  Sat      44      45     45.7      44      61
2  2016      1    3  Sun      45      44     45.8      41      56

In [38]:
from datetime import datetime
import pandas as pd 

df['date'] = pd.to_datetime(df[['year','month','day']])
df2 = df[df['date']<='2016-09-01'].sort_values(by='date')

print(f"2016년 9월 이후 온도의 평균 : {round(df2['actual'].mean(),1)}")

2016년 9월 이후 온도의 평균 : 65.0

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오 (Target : 1일 확률)  

제출형식은 ID, prob 두 칼럼만 존재해야 한다. (평가지표  : AUC)

In [46]:
import pandas as pd 
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_test.csv")

In [40]:
# EDA
display(train.head(3))
display(test.head(3))

print(train.info())

,level_0,ID,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,target
0,0,249,11.52,14.93,73.87,406.3,0.10130,0.07808,0.043280,0.029290,...,21.19,80.88,491.8,0.1389,0.15820,0.180400,0.09608,0.2664,0.07809,1
1,1,58,13.05,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,...,22.25,90.24,624.1,0.1021,0.06191,0.001845,0.01111,0.2439,0.06289,1
2,2,476,14.20,20.53,92.41,618.4,0.08931,0.11080,0.050630,0.030580,...,27.26,112.10,828.5,0.1153,0.34290,0.251200,0.13390,0.2534,0.07858,1

,level_0,ID,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,target
0,0,421,14.69,13.98,98.22,656.1,0.1031,0.18360,0.14500,0.0630,...,18.34,114.10,809.2,0.1312,0.3635,0.3219,0.1108,0.2827,0.09208,1
1,1,47,13.17,18.66,85.98,534.6,0.1158,0.12310,0.12260,0.0734,...,27.95,102.80,759.4,0.1786,0.4166,0.5006,0.2088,0.3900,0.11790,0
2,2,292,12.95,16.02,83.14,513.7,0.1005,0.07943,0.06155,0.0337,...,19.93,88.81,585.4,0.1483,0.2068,0.2241,0.1056,0.3380,0.09584,1

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   level_0                  398 non-null    int64
 1   ID                       398 non-null    int64
 2   mean_radius              398 non-null    float64
 3   mean_texture             398 non-null    float64
 4   mean_perimeter           398 non-null    float64
 5   mean_area                398 non-null    float64
 6   mean_smoothness          398 non-null    float64
 7   mean_compactness         398 non-null    float64
 8   mean_concavity           398 non-null    float64
 9   mean_concave_points      398 non-null    float64
 10  mean_symmetry            398 non-null    float64
 11  mean_fractal_dimension   398 non-null    float64
 12  radius_error             398 non-null    float64
 13  texture_error            398 non-null    float64
 14  perimeter_error          398 non-null    float64
 15  area_error               398 non-null    float64
 16  smoothness_error         398 non-null    float64
 17  compactness_error        398 non-null    float64
 18  concavity_error          398 non-null    float64
 19  concave_points_error     398 non-null    float64
 20  symmetry_error           398 non-null    float64
 21  fractal_dimension_error  378 non-null    float64
 22  worst_radius             398 non-null    float64
 23  worst_texture            398 non-null    float64
 24  worst_perimeter          398 non-null    float64
 25  worst_area               398 non-null    float64
 26  worst_smoothness         398 non-null    float64
 27  worst_compactness        398 non-null    float64
 28  worst_concavity          398 non-null    float64
 29  worst_concave_points     398 non-null    float64
 30  worst_symmetry           398 non-null    float64
 31  worst_fractal_dimension  398 non-null    float64
 32  target                   398 non-null    int64
dtypes: float64(30), int64(3)
memory usage: 102.7 KB
None

In [41]:
print(train.isnull().sum())
print(test.isnull().sum())

level_0                     0
ID                          0
mean_radius                 0
mean_texture                0
mean_perimeter              0
mean_area                   0
mean_smoothness             0
mean_compactness            0
mean_concavity              0
mean_concave_points         0
mean_symmetry               0
mean_fractal_dimension      0
radius_error                0
texture_error               0
perimeter_error             0
area_error                  0
smoothness_error            0
compactness_error           0
concavity_error             0
concave_points_error        0
symmetry_error              0
fractal_dimension_error    20
worst_radius                0
worst_texture               0
worst_perimeter             0
worst_area                  0
worst_smoothness            0
worst_compactness           0
worst_concavity             0
worst_concave_points        0
worst_symmetry              0
worst_fractal_dimension     0
target                      0
dtype: int64
level_0                     0
ID                          0
mean_radius                 0
mean_texture                0
mean_perimeter              0
mean_area                   0
mean_smoothness             0
mean_compactness            0
mean_concavity              0
mean_concave_points         0
mean_symmetry               0
mean_fractal_dimension      0
radius_error                0
texture_error               0
perimeter_error             0
area_error                  0
smoothness_error            0
compactness_error           0
concavity_error             0
concave_points_error        0
symmetry_error              0
fractal_dimension_error    11
worst_radius                0
worst_texture               0
worst_perimeter             0
worst_area                  0
worst_smoothness            0
worst_compactness           0
worst_concavity             0
worst_concave_points        0
worst_symmetry              0
worst_fractal_dimension     0
target                      0
dtype: int64

In [43]:
print(train.shape)
print(test.shape)

(398, 33)
(171, 33)

In [44]:
display(train['fractal_dimension_error'])

0      0.002784
1      0.002990
2      0.002744
3      0.002234
4      0.001982
         ...
393    0.003224
394    0.002360
395    0.006299
396    0.002925
397    0.001777
Name: fractal_dimension_error, Length: 398, dtype: float64

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_2_test.csv")

imputer = SimpleImputer(strategy='most_frequent')
train[['fractal_dimension_error']] = imputer.fit_transform(train[['fractal_dimension_error']])
test[['fractal_dimension_error']] = imputer.transform(test[['fractal_dimension_error']])

train_X = train.drop(['target','level_0','ID'],axis=1)
train_y = train['target']
test_X = test.drop(['target','level_0','ID'],axis=1)
test_y = test['target']

train_X, valid_X, train_y, valid_y = train_test_split(train_X,train_y,test_size=0.3,random_state=42)

from sklearn.ensemble import RandomForestClassifier # AUC 는 Classifier
rf = RandomForestClassifier()
rf.fit(train_X,train_y)

# 검증데이터로 미리 파악
from sklearn.metrics import roc_auc_score
valid_predict_proba = rf.predict_proba(valid_X)[:,1] # 정답이 1일 확률
valid_auc = roc_auc_score(valid_y,valid_predict_proba)
print(f"검증된 auc 점수 : {round(valid_auc,1)}")

# Test 검수
prediction = rf.predict_proba(test_X)[:,1]
AUC = roc_auc_score(test_y,prediction)
print(f"test 데이터의 AUC: {round(AUC,3)}")
test_id = test['ID']

result = pd.DataFrame({'ID' : test_id, 'prob' : prediction})
display(result.head(3))

검증된 auc 점수 : 1.0
test 데이터의 AUC: 0.985

    ID  prob
0  421  0.49
1   47  0.18
2  292  1.00

# 작업형 제3유형

어느 학교에서 학생들의 공부 시간과 시험 점수 간의 상관관계를 조사하고자 한다. 50명의 학생을 대상으로 하루 평균 공부 시간과 최근 시험 점수를 조사하였다.  

1. 학생들의 공부 시간과 시험 점수의 평균, 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)  
2. 공부 시간과 시험 점수 간의 상관관계를 조사하기 위한 피어슨 상관계수를 계산하시오. (소수점 셋째 자리까지 반올림)  
3. p-value를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소수점 셋째 자리까지 반올림)

In [ ]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_3_1.csv")
display(df.head(3))

   study_hours  exam_scores
0     8.528105    66.045334
1     5.800314    78.869025
2     6.957476    69.891949

어느 마케팅 회사에서 세 가지 마케팅 캠페인 (A, B, C) 의 효과가 유의미하게 다른지를 조사하고자 한다. 각 캠페인에 대해 각각 50명의 고객을 랜덤으로 추출하여 만족도를 조사하였다.  

1. 각 캠페인의 만족도 점수의 평균, 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)  
2. 세 캠페인의 평균 만족도 점수가 유의미하게 다른지 검정하기 위해 ANOVA 검정을 수행하고, 검정 통계량을 계산하시오. (소수점 셋째 자리까지 반올림)  
3. p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value는 소수점 셋째 자리까지 반올림)

In [ ]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/5_3_2.csv")
display(df.head(3))

  campaign  satisfaction_score
0        A           87.640523
1        A           74.001572
2        A           79.787380