# 작업형 제1유형

다음 데이터에서 결측치가 존재하는 행을 모두 삭제하시오. 데이터의 상위 70%에 해당하는 데이터를 추출하고, PTRATIO 칼럼의 1분위수를 구하시오. (소수점 둘째 자리까지 반올림)

In [1]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_1_1.csv")
display(df.head(3))

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,NaN,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,NaN,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,NaN,392.83,4.03,34.7

건축연도(yearBuilt) 가 1991 ~ 2000 년이면서 평균 학교등급(avgSchoolRating)이 평균 이하인 주택id(uid)와 건축연도 2001 ~ 2010 년에 평균 학교등급이 평균 이상인 주택 id의 수를 구하시오.

In [2]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_1_2.csv")
display(df.head(3))

,uid,city,homeType,latitude,longitude,garageSpaces,hasSpa,yearBuilt,numOfPatioAndPorchFeatures,lotSizeSqFt,avgSchoolRating,MedianStudentsPerTeacher,numOfBathrooms,numOfBedrooms,priceRange
0,6761,austin,Single Family,NaN,-97.816811,2,False,1981,0.0,9757.0,4.0,13,3.0,3,350000-450000
1,15045,austin,Single Family,NaN,-97.752731,2,False,1951,0.0,10846.0,7.0,16,3.0,4,650000+
2,11109,austin,Single Family,NaN,-97.699669,0,False,1954,0.0,9016.0,5.0,15,2.0,3,350000-450000

위 데이터의 각 칼럼 중 결측치가 가장 많은 칼럼을 출력하시오

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오. (Target : 이탈 여부 (Attrition_Flag) 가 Attrited Customer 일 확률)  
* 제출 형식은 ID, prob 두 칼럼만 존재해야 한다. (평가지표 : AUC)

In [3]:
import pandas as pd 
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_test.csv")

# 작업형 제3유형

어느 회사에서 두 부서 (A와 B) 직원들의 주간 근무 시간 평균이 유믜미하게 다른지를 조사하고자 한다. 각 부서에서 각각 30명의 직원을 랜덤으로 추출하여 주간 근무 시간을 조사하였다. 

(1) 두 부서의 평균과 표춘편차를 구하시오. (소수점 둘째 자리까지 반올림)  
(2) 두 부서의 평균 근무시간이 유의미하게 다른지 검정하기 위해 독립 표본 t-검정을 수행하고, 검정통계량을 계산하시오. (소수점 둘째 자리까지 반올림)  
(3) p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소수점 둘째 자리까지 반올림)

In [4]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_3_1.csv")
display(df.head(3))

  department  hours_worked
0          A     48.820262
1          A     42.000786
2          A     44.893690

어느 제조업체에서 세 공장 (A, B, C) 에서 생산된 제품의 품질 점수가 유의미하게 다른지를 조사하고자 한다. 각 공장에서 각각 30개의 제품을 랜덤으로 추출하여 품질 점수를 조사하였다.  

(1) 세 공장 품질 점수의 평균과 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)    
(2) 두 부서의 평균 근무 시간이 유의미하게 다른지 검정하기 위해 크루스칼-왈리스 검정을 수행하고, 검정통계량을 계산하시오. (소수점 둘째 자리까지 반올림)  
(3) p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 둘째자리까지 반올림)

In [ ]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_3_2.csv")
display(df.head(3))