# 작업형 제1유형

다음 데이터에서 결측치가 존재하는 행을 모두 삭제하시오. 데이터의 상위 70%에 해당하는 데이터를 추출하고, PTRATIO 칼럼의 1분위수를 구하시오. (소수점 둘째 자리까지 반올림)

In [1]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_1_1.csv")
display(df.head(3))

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,NaN,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,NaN,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,NaN,392.83,4.03,34.7

In [3]:
print(df.isnull().sum())
print(len(df))

CRIM        0
ZN          0
INDUS       0
CHAS        0
NOX         0
RM          0
AGE         0
DIS         0
RAD         0
TAX         0
PTRATIO    11
B           0
LSTAT       0
PRICE       0
dtype: int64
506

In [14]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_1_1.csv")
df = df.dropna()
df = df.sort_values(['PTRATIO'],ascending=False)
print(len(df)*0.7)

df2 = df[:346]
Q1 = df2['PTRATIO'].quantile(0.7)
print(f"상위 70% 에 해당하는 데이터의 PTRATIO 칼럼의 1분위 수 : {round(Q1,2)}")

346.5
상위 70% 에 해당하는 데이터의 PTRATIO 칼럼의 1분위 수 : 20.2

건축연도(yearBuilt) 가 1991 ~ 2000 년이면서 평균 학교등급(avgSchoolRating)이 평균 이하인 주택id(uid)와 건축연도 2001 ~ 2010 년에 평균 학교등급이 평균 이상인 주택 id의 수를 구하시오.

In [27]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_1_2.csv")
display(df.head(3))
#print(df.isnull().sum())

#df['yearBuilt'] = df['yearBuilt'].dt.year
avg_rate = df['avgSchoolRating'].mean()
df2 = df[(1991 <= df['yearBuilt']) & (df['yearBuilt'] <= 2000) & (avg_rate >= df['avgSchoolRating'])]
print(f"1991 ~ 2000 년 사이에 건축되었으면서 학교 등급이 평균 이하인 주택 수 : {len(df2)}")

df3 = df[(df['yearBuilt']>=2001) & (df['yearBuilt'] <= 2010) & (df['avgSchoolRating'] >= avg_rate)]
print(f"2001 ~ 2010 년 사이에 건축되었으면서 학교 등급이 평균 이상인 주택 수 : {len(df3)}")

,uid,city,homeType,latitude,longitude,garageSpaces,hasSpa,yearBuilt,numOfPatioAndPorchFeatures,lotSizeSqFt,avgSchoolRating,MedianStudentsPerTeacher,numOfBathrooms,numOfBedrooms,priceRange
0,6761,austin,Single Family,NaN,-97.816811,2,False,1981,0.0,9757.0,4.0,13,3.0,3,350000-450000
1,15045,austin,Single Family,NaN,-97.752731,2,False,1951,0.0,10846.0,7.0,16,3.0,4,650000+
2,11109,austin,Single Family,NaN,-97.699669,0,False,1954,0.0,9016.0,5.0,15,2.0,3,350000-450000

1991 ~ 2000 년 사이에 건축되었으면서 학교 등급이 평균 이하인 주택 수 : 21
2001 ~ 2010 년 사이에 건축되었으면서 학교 등급이 평균 이상인 주택 수 : 55

위 데이터의 각 칼럼 중 결측치가 가장 많은 칼럼을 출력하시오

In [34]:
nan_count=df.isnull().sum().reset_index()
print(nan_count)

print("위 데이터의 각 칼럼중 결측치가 가장 많은 칼럼 : ")
nan_max = nan_count.idxmax()[0]
print(nan_count.iloc[nan_max,0])
print("\n",nan_count.idxmax()[0])

                         index   0
0                          uid   0
1                         city   0
2                     homeType   0
3                     latitude  11
4                    longitude  21
5                 garageSpaces   0
6                       hasSpa   0
7                    yearBuilt   0
8   numOfPatioAndPorchFeatures  31
9                  lotSizeSqFt   0
10             avgSchoolRating   0
11    MedianStudentsPerTeacher   0
12              numOfBathrooms   0
13               numOfBedrooms   0
14                  priceRange   0
위 데이터의 각 칼럼중 결측치가 가장 많은 칼럼 :
numOfPatioAndPorchFeatures

 8

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오. (Target : 이탈 여부 (Attrition_Flag) 가 Attrited Customer 일 확률)  
* 제출 형식은 ID, prob 두 칼럼만 존재해야 한다. (평가지표 : AUC)

In [36]:
import pandas as pd 
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_test.csv")

In [38]:
print(train.isnull().sum())
print(test.isnull().sum())

ID                        0
Attrition_Flag            0
Gender                    0
Customer_Age              0
Income_Category           0
Card_Category             0
Credit_Limit              0
Total_Revolving_Bal       0
Avg_Utilization_Ratio     0
Avg_Open_To_Buy           0
Months_Inactive_12_mon    0
dtype: int64
ID                        0
Attrition_Flag            0
Gender                    0
Customer_Age              0
Income_Category           0
Card_Category             0
Credit_Limit              0
Total_Revolving_Bal       0
Avg_Utilization_Ratio     0
Avg_Open_To_Buy           0
Months_Inactive_12_mon    0
dtype: int64

In [39]:
display(train.head(3))
print(train.info())

,ID,Attrition_Flag,Gender,Customer_Age,Income_Category,Card_Category,Credit_Limit,Total_Revolving_Bal,Avg_Utilization_Ratio,Avg_Open_To_Buy,Months_Inactive_12_mon
0,9251,Existing Customer,M,35,$40K - $60K,Gold,22725.0,808,0.036,21917.0,1
1,8091,Attrited Customer,F,49,$40K - $60K,Blue,2655.0,2283,0.860,372.0,2
2,8762,Existing Customer,M,41,$80K - $120K,Blue,12578.0,2517,0.200,10061.0,3

<class 'pandas.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      354 non-null    int64
 1   Attrition_Flag          354 non-null    str
 2   Gender                  354 non-null    str
 3   Customer_Age            354 non-null    int64
 4   Income_Category         354 non-null    str
 5   Card_Category           354 non-null    str
 6   Credit_Limit            354 non-null    float64
 7   Total_Revolving_Bal     354 non-null    int64
 8   Avg_Utilization_Ratio   354 non-null    float64
 9   Avg_Open_To_Buy         354 non-null    float64
 10  Months_Inactive_12_mon  354 non-null    int64
dtypes: float64(3), int64(4), str(4)
memory usage: 30.6 KB
None

In [82]:
import pandas as pd 
train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_2_test.csv")
#display(train.head(3))

# target 은 자체 onehot
print(train['Attrition_Flag'].unique())
def target(df) : 
    if df == "Existing Customer" :
        return 0
    elif df == "Attrited Customer" :
        return 1
train['Attrition_Flag'] = train['Attrition_Flag'].apply(target)
test['Attrition_Flag'] = test['Attrition_Flag'].apply(target)

train_X = train.drop(['ID'],axis=1)
train_y = train['Attrition_Flag']
test_X = test.drop(['ID'],axis=1)
test_y = test['Attrition_Flag']

from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
cat_cols = train_X.select_dtypes('object').columns.to_list()
num_cols = train_X.select_dtypes('number').columns.to_list()

train_X_onehot = onehot.fit_transform(train[cat_cols])
test_X_onehot = onehot.transform(test[cat_cols])

import numpy as np 
train_X_pre = np.concatenate([train_X_onehot,train_X[num_cols]],axis=1)
test_X_pre = np.concatenate([test_X_onehot,test_X[num_cols]],axis=1)

# RandomForest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(train_X_pre,train_y)
prediction = rf.predict_proba(test_X_pre)[:,1]

from sklearn.metrics import roc_auc_score
auc = roc_auc_score(test_y,prediction)

print(f"AUC : {round(auc,1)}")

test_id = test['ID'] 
result = pd.DataFrame({'ID':test_id,'proba':prediction})

display(result.head(5))

<StringArray>
['Existing Customer', 'Attrited Customer']
Length: 2, dtype: str
AUC : 1.0

C:\Users\user\AppData\Local\Temp\ipykernel_1940\3847150074.py:24: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = train_X.select_dtypes('object').columns.to_list()

     ID  proba
0  6086   0.02
1  6630   0.07
2  4292   0.00
3  7044   0.00
4  2619   0.76

# 작업형 제3유형

어느 회사에서 두 부서 (A와 B) 직원들의 주간 근무 시간 평균이 유믜미하게 다른지를 조사하고자 한다. 각 부서에서 각각 30명의 직원을 랜덤으로 추출하여 주간 근무 시간을 조사하였다. 

(1) 두 부서의 평균과 표춘편차를 구하시오. (소수점 둘째 자리까지 반올림)  
(2) 두 부서의 평균 근무시간이 유의미하게 다른지 검정하기 위해 독립 표본 t-검정을 수행하고, 검정통계량을 계산하시오. (소수점 둘째 자리까지 반올림)  
(3) p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소수점 둘째 자리까지 반올림)

In [83]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_3_1.csv")
display(df.head(3))

  department  hours_worked
0          A     48.820262
1          A     42.000786
2          A     44.893690

In [84]:
print("A 부서의 주간 근무시간")
df_A = df[(df['department']=="A")]
df_B = df[(df['department']=="B")]
A_mean = df_A['hours_worked'].mean()
A_std = df_A['hours_worked'].std()
B_mean = df_B['hours_worked'].mean()
B_std = df_B['hours_worked'].std()
print(f"평균 : {round(A_mean,2)}, 표준편차 : {round(A_std,2)}")
print("B 부서의 주간 근무시간")
print(f"평균 : {round(B_mean,2)}, 표준편차 : {round(B_std,2)}")

A 부서의 주간 근무시간
평균 : 42.21, 표준편차 : 5.5
B 부서의 주간 근무시간
평균 : 43.55, 표준편차 : 4.57

In [86]:
from scipy.stats import ttest_ind 
# 독립표본 t-검정
statistic, pvalue = ttest_ind(df_A['hours_worked'],df_B['hours_worked'])
print(f"검정통계량 : {round(statistic,2)}")
if pvalue < 0.05 : 
    print("귀무가설을 기각합니다.")
else :
    print("귀무가설을 채택합니다.")

검정통계량 : -1.02
귀무가설을 채택합니다.

어느 제조업체에서 세 공장 (A, B, C) 에서 생산된 제품의 품질 점수가 유의미하게 다른지를 조사하고자 한다. 각 공장에서 각각 30개의 제품을 랜덤으로 추출하여 품질 점수를 조사하였다.  

(1) 세 공장 품질 점수의 평균과 표준편차를 구하시오. (소수점 둘째 자리까지 반올림)    
(2) 두 부서의 평균 근무 시간이 유의미하게 다른지 검정하기 위해 크루스칼-왈리스 검정을 수행하고, 검정통계량을 계산하시오. (소수점 둘째 자리까지 반올림)  
(3) p-value 를 바탕으로 유의수준 5% 에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 둘째자리까지 반올림)

In [87]:
import pandas as pd 
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/4_3_2.csv")
display(df.head(3))

  factory  quality_score
0       A      87.640523
1       A      74.001572
2       A      79.787380

In [88]:
df_A = df[(df['factory']=='A')]
df_B = df[(df['factory']=='B')]
df_C = df[(df['factory']=='C')]

print(f"공장 A의 표준 : {round(df_A['quality_score'].mean(),2)}, 표준편차 : {round(df_A['quality_score'].std(),2)}")
print(f"공장 B의 표준 : {round(df_B['quality_score'].mean(),2)}, 표준편차 : {round(df_B['quality_score'].std(),2)}")
print(f"공장 C의 표준 : {round(df_C['quality_score'].mean(),2)}, 표준편차 : {round(df_C['quality_score'].std(),2)}")

# 크루스칼-왈리스검정
group1,group2,group3 = df_A['quality_score'],df_B['quality_score'],df_C['quality_score']
from scipy.stats import kruskal
statistic, pvalue = kruskal(group1,group2,group3)
print(f"검정통계량 : {round(statistic,2)}")
if pvalue < 0.05 : 
    print("귀무가설을 기각합니다.")
else :
    print("귀무가설을 채택합니다.")

공장 A의 표준 : 74.43, 표준편차 : 11.0
공장 B의 표준 : 72.1, 표준편차 : 9.14
공장 C의 표준 : 78.66, 표준편차 : 9.65
검정통계량 : 5.93
귀무가설을 채택합니다.